const IMAGE_TOOLS=[
['image-compress','🗜️','Image Compressor','Compress an image while keeping the uploaded format unless you choose another format.'],
['image-resize','↔️','Image Resizer','Resize an image to exact dimensions with before and after preview.'],
['image-convert','🖼️','Image Converter','Convert images to JPG, PNG or WebP.'],
['image-info','🔎','Image Info','Check dimensions, file type and file size.'],
['image-crop','✂️','Crop Image','Select the crop area directly on your image with a live draggable box.'],
['image-rotate','🔄','Rotate & Flip Image','Rotate or flip an image and preview the result.'],
['image-percent','📐','Resize by Percentage','Scale an image by percentage while keeping proportions.'],
['image-target','🎯','Compress to KB','Target a specific file size in KB.'],
['image-passport','🪪','Passport Photo Resizer','Resize to common photo dimensions with DPI control.'],
['image-base64','64','Image to Base64','Create a complete Base64 data URL and verify every decoded byte.'],
['base64-image','🧩','Base64 to Image','Decode a Base64 image data URL and preview it.'],
['image-filter','✨','Image Adjustments','Live brightness, contrast, saturation, exposure, warmth, hue, blur and more.'],
['image-border','🖼','Add Image Border','Add a custom border around an image.'],
['image-text','T','Add Text to Image','Place text anywhere on an image with live preview.'],
['image-watermark','💧','Watermark Studio','Add watermarks or clean authorized images with live mask refinement and full-resolution export.'],
['image-exif','🧹','Remove Image Metadata','Re-export an image locally to strip common metadata.'],
['image-color','🎨','Image Color Picker','Click an image to inspect pixel color.'],
['print-size','📏','DPI / Print Size Calculator','Convert pixel dimensions and DPI into physical print size.'],
['image-bg-remove','🪄','Background Remover','Automatically remove portrait and simple outer backgrounds into a transparent PNG.'],
['image-grayscale','◐','Grayscale Image','Convert an image to grayscale with live preview.'],
['image-blur','🌫️','Blur Image','Apply blur with live preview.'],
['image-sharpen','🔺','Sharpen Image','Control sharpening strength with live preview.'],
['multi-resize','🗂️','Batch Image Resizer','Resize multiple images and download them together as ZIP.'],
['multi-compress','📦','Batch Image Compressor','Compress multiple images and download them together as ZIP.']
];
const TOOL=Object.fromEntries(IMAGE_TOOLS.map(x=>[x[0],{id:x[0],icon:x[1],name:x[2],desc:x[3]}]));
const $=id=>document.getElementById(id); const id=document.body.dataset.tool; const t=TOOL[id];
const supportedOut=new Set(['image/jpeg','image/png','image/webp']);
const esc=s=>String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const extForType=type=>type==='image/jpeg'?'jpg':type==='image/png'?'png':type==='image/webp'?'webp':type==='image/avif'?'avif':'png';
const actionNames={'image-compress':'Compressed','image-resize':'Resized','image-convert':'Converted','image-crop':'Cropped','image-rotate':'Rotated','image-percent':'Resized','image-target':'Compressed','image-passport':'Passport','image-filter':'Adjusted','image-border':'Border','image-text':'Text','image-watermark':'Watermark','image-exif':'Clean','image-bg-remove':'BGRemoved','image-grayscale':'Grayscale','image-blur':'Blurred','image-sharpen':'Sharpened','base64-image':'Decoded','multi-resize':'Resized','multi-compress':'Compressed'};
function typeFor(file,selection='same',transparent=false){if(selection&&selection!=='same')return selection;if(transparent)return'image/png';return supportedOut.has(file?.type)?file.type:(file?.type==='image/jpg'?'image/jpeg':'image/png')}
function outName(tool,type,index){const name=(TOOL[tool]?.name||tool||'Image').replace(/[^a-z0-9]+/gi,'_').replace(/^_+|_+$/g,'');const act=(actionNames[tool]||'Processed').replace(/[^a-z0-9]+/gi,'_');return `DoKitly_${name}_${act}${index?`_${index}`:''}.${extForType(type)}`}
function humanSize(n){if(!Number.isFinite(n))return'';return n>=1024*1024?(n/1024/1024).toFixed(2)+' MB':(n/1024).toFixed(1)+' KB'}
function loadExternal(src,globalName){return new Promise((res,rej)=>{if(globalName&&window[globalName])return res();const old=[...document.scripts].find(x=>x.src===src);if(old){old.addEventListener('load',()=>res(),{once:true});old.addEventListener('error',()=>rej(Error('Decoder failed to load.')),{once:true});return}const s=document.createElement('script');s.src=src;s.async=true;s.onload=()=>res();s.onerror=()=>rej(Error('Decoder failed to load.'));document.head.appendChild(s)})}
function imageFromBlob(blob){return new Promise((res,rej)=>{const u=URL.createObjectURL(blob),im=new Image();im.onload=()=>res({img:im,url:u});im.onerror=()=>{URL.revokeObjectURL(u);rej(Error('This image could not be opened in the browser.'))};im.src=u})}
async function readImage(file){if(!file)throw Error('Please select an image first.');const n=(file.name||'').toLowerCase(),type=(file.type||'').toLowerCase();if(/\.tiff?$/.test(n)||/image\/tiff/.test(type)){await loadExternal('https://cdn.jsdelivr.net/npm/utif@3.1.0/UTIF.min.js','UTIF');const buf=await file.arrayBuffer(),ifds=UTIF.decode(buf);if(!ifds.length)throw Error('TIFF contains no readable frame.');UTIF.decodeImage(buf,ifds[0]);const rgba=UTIF.toRGBA8(ifds[0]),c=document.createElement('canvas');c.width=ifds[0].width;c.height=ifds[0].height;c.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(rgba),c.width,c.height),0,0);const blob=await new Promise(r=>c.toBlob(r,'image/png'));c.width=c.height=1;return imageFromBlob(blob)}if(/\.hei[cf]$/.test(n)||/image\/hei[cf]/.test(type)){await loadExternal('https://cdn.jsdelivr.net/npm/heic2any@0.0.4/dist/heic2any.min.js','heic2any');let out=await heic2any({blob:file,toType:'image/png'});if(Array.isArray(out))out=out[0];return imageFromBlob(out)}return imageFromBlob(file)}
function blobFromCanvas(c,type,quality=.92){return new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(Error('This browser cannot export the selected format.')),type,quality))}
function canvasDraw(img,w=img.width,h=img.height,type='image/png'){const c=document.createElement('canvas');c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));const x=c.getContext('2d',{willReadFrequently:true});if(type==='image/jpeg'){x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height)}x.drawImage(img,0,0,c.width,c.height);return c}
function fileInput(label='Select image',multi=false){return `<div class="dropzone upload-row global-upload-row"><div class="upload-name" id="uploadName" title="${label}">${label}</div><label class="file-pick-btn" for="fileInput">Choose File</label><input id="fileInput" class="native-file-input" type="file" accept="image/*" ${multi?'multiple':''}><div id="beforeStage" class="upload-thumb"><span class="empty">Preview</span></div></div>`}
function formatSelect(includeSame=true,idn='format'){return `<div class="field"><label>Output format</label><select id="${idn}">${includeSame?'<option value="same">Same as upload</option>':''}<option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select>${includeSame?'<div class="format-note">Changes only when you choose another format.</div>':''}</div>`}
function pageShell(inner){return `<div class="it-title"><span class="ico">${t.icon}</span><div><h1>${t.name}</h1><p>${t.desc}</p></div></div><section class="it-panel">${inner}</section>`}
function signedValue(v,unit=''){const n=Number(v);return `${n>0?'+':''}${n}${unit}`}
function compactRange(idn,label,min,max,value,unit='',icon='◉',step=1){const signed=min<0,maxTxt=signed?signedValue(value,unit):`${value}${unit}`;return `<div class="control-card simple-control-card branded-range" data-control="${idn}"><div class="control-top"><span class="control-icon">${icon}</span><label for="${idn}">${label}</label><output id="out-${idn}">${maxTxt}</output><button class="mini-reset" type="button" data-range-reset="${idn}" data-default="${value}" title="Reset ${label}">↺</button></div><div class="control-bottom"><button class="nudge" type="button" data-range-nudge="${idn}:-${step}">−</button><input id="${idn}" data-ui-range data-unit="${unit}" data-signed="${signed?'1':'0'}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"><button class="nudge" type="button" data-range-nudge="${idn}:${step}">+</button></div></div>`}
function adjustmentControls(){
 const groups=[['Light','☀️',[['brightness','Brightness',-100,100,0,'','◐'],['exposure','Exposure',-50,50,0,'','◒'],['contrast','Contrast',-100,100,0,'','◑'],['highlights','Highlights',-100,100,0,'','✦'],['shadows','Shadows',-100,100,0,'','◼']]],['Color','🎨',[['saturate','Saturation',-100,100,0,'','◉'],['vibrance','Vibrance',-100,100,0,'','✺'],['warmth','Warmth',-100,100,0,'','♨'],['tint','Tint',-100,100,0,'','◈'],['hue','Hue',-180,180,0,'°','◎']]],['Effects','✨',[['blur','Blur',0,20,0,'px','◌'],['sharpen','Sharpen',0,100,0,'','△'],['sepia','Sepia',0,100,0,'','◍'],['grayscale','Grayscale',0,100,0,'','◐'],['opacity','Opacity',-90,0,0,'','◫']]]];
 const presets=`<div class="preset-bar"><span>Quick looks</span><div class="preset-chips"><button type="button" data-preset="auto">Auto</button><button type="button" data-preset="vivid">Vivid</button><button type="button" data-preset="warm">Warm</button><button type="button" data-preset="cool">Cool</button><button type="button" data-preset="bw">B&W</button></div></div>`;
 return presets+`<div class="adjustment-groups">${groups.map(([name,ico,rows])=>`<section class="control-group"><div class="control-group-head"><span>${ico}</span><b>${name}</b></div><div class="control-list">${rows.map(r=>`<div class="control-card" data-control="${r[0]}"><div class="control-top"><span class="control-icon">${r[6]}</span><label for="adj-${r[0]}">${r[1]}</label><output id="out-${r[0]}">${signedValue(r[4],r[5])}</output><button class="mini-reset" type="button" data-reset-adj="${r[0]}" title="Reset ${r[1]}">↺</button></div><div class="control-bottom"><button class="nudge" type="button" data-nudge="${r[0]}:-1">−</button><input id="adj-${r[0]}" data-adj="${r[0]}" data-unit="${r[5]}" type="range" min="${r[2]}" max="${r[3]}" value="${r[4]}"><button class="nudge" type="button" data-nudge="${r[0]}:1">+</button></div></div>`).join('')}</div></section>`).join('')}</div>`}
function editorPreviewHTML(label='Processed Preview'){return `<aside class="editor-preview"><div class="live-preview-card"><div class="preview-head"><div><b>${label}</b><small>Live • stays visible while you edit</small></div><span><small id="afterMeta">Waiting</small> <button class="zoom-btn" data-zoom="after" hidden>Zoom</button></span></div><div class="preview-stage editor-after-stage" id="afterStage"><div class="empty">Upload an image to start.</div></div></div></aside>`}
function editorWrap(controls,label='Processed Preview'){return `<div class="editor-layout"><div class="editor-controls">${fileInput()}${controls}</div>${editorPreviewHTML(label)}</div>`}
function textControls(watermark=false){return `<div class="form-grid"><div class="field wide"><label>Text</label><input id="overlayText" value="${watermark?'DoKitly':'Your text'}"></div><div class="field"><label>Size (px)</label><input id="textSize" type="number" value="48" min="8" max="500"></div><div class="field"><label>Color</label><input id="textColor" type="color" value="#ffffff"></div><div class="field"><label>Position</label><select id="position"><option value="tl">Top Left</option><option value="tc">Top Center</option><option value="tr">Top Right</option><option value="cl">Center Left</option><option value="cc" selected>Center</option><option value="cr">Center Right</option><option value="bl">Bottom Left</option><option value="bc">Bottom Center</option><option value="br">Bottom Right</option><option value="custom">Custom X / Y</option></select></div><div class="field"><label>Style</label><select id="fontStyle"><option value="normal">Regular</option><option value="bold" selected>Bold</option><option value="italic">Italic</option><option value="bolditalic">Bold Italic</option></select></div></div>${compactRange('opacity','Opacity',0,100,watermark?45:100,'%','◫')}${compactRange('rotation','Rotation',-180,180,0,'°','↻')}${compactRange('offsetX','Custom X',-100,100,0,'','↔')}${compactRange('offsetY','Custom Y',-100,100,0,'','↕')}`}
function render(){let inner='';
 if(id==='print-size') inner=`<div class="form-grid"><div class="field"><label>Width (px)</label><input id="printW" type="number" value="3000"></div><div class="field"><label>Height (px)</label><input id="printH" type="number" value="2000"></div><div class="field"><label>DPI</label><input id="printDpi" type="number" value="300"></div></div><div class="btns"><button class="btn" id="processBtn">Calculate</button></div><div class="status" id="status">Enter values and calculate.</div>`;
 else if(id==='image-info') inner=`${fileInput()}<div class="status" id="infoOut">Upload an image.</div>`;
 else if(id==='image-base64') inner=`${fileInput()}<div class="btns"><button class="btn" id="processBtn">Convert to Base64</button><button class="btn-secondary" id="copyBtn" disabled>Copy full Base64</button><button class="btn-secondary" id="saveBase64Btn" disabled>Save .txt</button><button class="btn-secondary" id="openVerifiedBtn" disabled>Open verified image</button></div><div class="field base64-field"><label>Complete Base64 data URL <small id="base64Count"></small></label><textarea id="base64Out" readonly spellcheck="false"></textarea></div><div class="status" id="status">Base64 is generated from exact file bytes and decoded back before verification.</div><div class="verify-card"><div class="preview-head"><b>Verified decoded preview</b><small id="afterMeta">Waiting</small></div><div class="preview-stage" id="afterStage"><div class="empty">Verified image appears here.</div></div></div>`;
 else if(id==='base64-image') inner=`<div class="field"><label>Paste Base64 data URL</label><textarea id="base64In" placeholder="data:image/png;base64,..." spellcheck="false"></textarea></div><div class="btns"><button class="btn" id="processBtn">Preview image</button></div><div class="status" id="status">Paste a complete image data URL.</div><div class="verify-card"><div class="preview-head"><b>Decoded image</b><small id="afterMeta">Waiting</small></div><div class="preview-stage" id="afterStage"><div class="empty">Preview appears here.</div></div></div>`;
 else if(id==='image-color') inner=`${fileInput()}<div class="color-tool-help"><b>Click the thumbnail preview to pick a color</b><div class="color-readout"><div class="swatch" id="swatch"></div><div><b id="hexOut">#—</b><div class="note" id="rgbOut">RGB —</div></div></div></div>`;
 else if(id==='multi-resize'||id==='multi-compress') inner=`<div class="editor-layout"><div class="editor-controls">${fileInput('Select multiple images',true)}${id==='multi-compress'?compactRange('quality','Quality',10,100,75,'%','◉'):''}<div class="form-grid">${id==='multi-resize'?'<div class="field"><label>Maximum width (px)</label><input id="batchWidth" type="number" value="1200" min="50"></div>':''}${formatSelect(true)}</div><div class="btns"><button class="btn" id="processBtn">Process batch</button><button class="btn-secondary" id="cancelBatchBtn" type="button">Cancel</button><button class="btn-secondary" id="retryBatchBtn" type="button" disabled>Retry failed</button></div><div class="batch-list" id="batchList"></div><div class="status" id="status">Preview shows the first selected image.</div></div>${editorPreviewHTML('First Image Preview')}</div>`;
 else {
  let controls='';
  if(id==='image-filter') controls=`${adjustmentControls()}<div class="form-grid editor-format">${formatSelect(true)}</div><div class="btns"><button class="btn" id="processBtn">Process result</button><button class="btn-secondary" id="undoAdjustBtn" type="button">Undo</button><button class="btn-secondary" id="redoAdjustBtn" type="button">Redo</button><button class="btn-secondary" id="resetBtn">Reset All</button></div><div class="status" id="status">Live preview is optimized for smooth editing. Full resolution is used on download.</div>`;
  else if(id==='image-grayscale') controls=`${compactRange('simpleLive','Grayscale',0,100,0,'','◐')}<div class="form-grid">${formatSelect(true)}</div><div class="btns"><button class="btn" id="processBtn">Process result</button></div><div class="status" id="status">Use slider, +/−, or keyboard arrow keys.</div>`;
  else if(id==='image-blur') controls=`${compactRange('simpleLive','Blur',0,20,0,'px','◌')}<div class="form-grid">${formatSelect(true)}</div><div class="btns"><button class="btn" id="processBtn">Process result</button></div><div class="status" id="status">Live blur preview; only one download button.</div>`;
  else if(id==='image-sharpen') controls=`${compactRange('sharpenAmount','Sharpen',0,100,0,'','△')}<div class="form-grid">${formatSelect(true)}</div><div class="btns"><button class="btn" id="processBtn">Process result</button></div><div class="status" id="status">Increase sharpening only as much as needed.</div>`;
  else if(id==='image-crop') controls=`<div class="ratio-row"><button data-ratio="free" class="active">Free</button><button data-ratio="1">1:1</button><button data-ratio="1.333333">4:3</button><button data-ratio="1.5">3:2</button><button data-ratio="1.777778">16:9</button><button data-ratio="0.5625">9:16</button></div><div class="crop-editor-card"><div class="preview-head"><b>Live crop selection</b><small id="cropMeta">Upload an image</small></div><div class="crop-stage" id="cropStage"><div class="empty">Crop box appears here.</div></div></div><div class="form-grid">${formatSelect(true)}</div><div class="btns"><button class="btn" id="processBtn">Process crop</button></div><div class="status" id="status">Drag the crop box or its corner. Preview on the right stays visible.</div>`;
  else if(id==='image-compress') controls=`${compactRange('quality','Quality',10,100,80,'%','◉')}<div class="form-grid"><div class="field"><label>Target size (optional KB)</label><input id="targetKB" type="number" min="1" placeholder="e.g. 100"></div><div class="field"><label>Width (optional px)</label><input id="width" type="number" min="1" placeholder="Original"></div><div class="field"><label>Height (optional px)</label><input id="height" type="number" min="1" placeholder="Original"></div>${formatSelect(true)}</div><div class="btns"><button class="btn" id="processBtn">Process compression</button></div><div class="status" id="status">Live preview updates without re-encoding on every slider step.</div>`;
  else if(id==='image-resize') controls=`<div class="form-grid"><div class="field"><label>Width (px)</label><input id="width" type="number" min="1" placeholder="e.g. 1200"></div><div class="field"><label>Height (px)</label><input id="height" type="number" min="1" placeholder="Auto"></div><div class="field"><label>Scale (%)</label><input id="resizePercent" type="number" min="1" max="1000" value="100"></div><div class="field"><label>Fit mode</label><select id="resizeFit"><option value="stretch">Exact / Stretch</option><option value="contain">Fit inside</option><option value="cover">Fill & crop</option></select></div><div class="field wide"><label><input id="lockRatio" type="checkbox" checked> Keep aspect ratio</label></div><div class="note wide" id="upscaleNote"></div>${formatSelect(true)}</div><div class="btns"><button class="btn" id="processBtn">Process resize</button></div><div class="status" id="status">Enter width or height; preview updates live.</div>`;
  else if(id==='image-convert') controls=`${compactRange('quality','Quality (JPG/WebP/AVIF)',10,100,90,'%','◉')}<div class="form-grid">${formatSelect(false)}<div class="field wide"><label><input id="allowFirstFrame" type="checkbox"> For an animated GIF/WebP, explicitly extract only the first frame</label></div></div><div class="btns"><button class="btn" id="processBtn">Process conversion</button></div><div class="status" id="status">Only formats this browser can genuinely encode are offered. Animation is never silently flattened.</div>`;
  else if(id==='image-rotate') controls=`<div class="form-grid"><div class="field"><label>Rotate</label><select id="rotate"><option value="0" selected>0° — Original</option><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></div><div class="field"><label>Flip</label><select id="flip"><option value="none">No flip</option><option value="h">Horizontal</option><option value="v">Vertical</option></select></div>${formatSelect(true)}</div><div class="btns"><button class="btn" id="processBtn">Process result</button></div><div class="status" id="status">0° keeps the uploaded orientation unchanged.</div>`;
  else if(id==='image-percent') controls=`${compactRange('percent','Scale',10,300,100,'%','↔',1)}<div class="form-grid">${formatSelect(true)}</div><div class="btns"><button class="btn" id="processBtn">Process resize</button></div><div class="status" id="status">100% is original size.</div>`;
  else if(id==='image-target') controls=`<div class="form-grid"><div class="field"><label>Target size (KB)</label><select id="targetSelect"><option>20</option><option>50</option><option selected>100</option><option>200</option><option>500</option><option value="custom">Custom</option></select></div><div class="field"><label>Custom KB</label><input id="targetCustom" type="number" min="1" placeholder="e.g. 75"></div><div class="field"><label>Output format</label><select id="format"><option value="same">Same as upload</option><option value="image/jpeg">JPG</option><option value="image/webp">WebP</option><option value="image/png">PNG</option></select></div></div><div class="btns"><button class="btn" id="processBtn">Compress Image</button><button class="btn-secondary" id="targetDownloadBtn" disabled>Download Image</button></div><div class="status" id="status">Set a target, compress, review the result, then download.</div>`;
  else if(id==='image-passport') controls=`<div class="form-grid"><div class="field"><label>Preset</label><select id="passportPreset"><option value="35,45">35 × 45 mm</option><option value="51,51">2 × 2 inch (51 × 51 mm)</option><option value="35,35">35 × 35 mm</option></select></div><div class="field"><label>DPI</label><input id="dpi" type="number" min="72" max="1200" value="300"></div><div class="field"><label>Background</label><select id="passportBg"><option value="keep">Keep original</option><option value="#ffffff">White</option><option value="#dceeff">Light Blue</option><option value="#3b82f6">Blue</option><option value="#e5e7eb">Light Grey</option><option value="#ef4444">Red</option></select></div><div class="field"><label>Target KB (optional)</label><input id="passportTargetKB" type="number" min="5" placeholder="e.g. 100"></div>${formatSelect(true)}</div>${compactRange('passportZoom','Zoom',70,220,110,'%','⌕')}${compactRange('passportX','Left / Right',-100,100,0,'','↔')}${compactRange('passportY','Up / Down',-100,100,-8,'','↕')}<div class="btns"><button class="btn-secondary" id="autoFaceBtn" type="button">Auto center face</button><button class="btn" id="processBtn">Process passport photo</button><button class="btn-secondary" id="passportSheetBtn" type="button">Printable 4×6 sheet</button></div><div class="status" id="status">Auto face centering uses the browser face detector where available. Use zoom/position for final framing. Presets are dimensions only; always verify the authority’s current rules.</div>`;
  else if(id==='image-border') controls=`<div class="form-grid"><div class="field"><label>Border width (px)</label><input id="borderW" type="number" value="20" min="0" max="1000"></div><div class="field"><label>Border color</label><input id="borderColor" type="color" value="#2563eb"></div>${formatSelect(true)}</div><div class="btns"><button class="btn" id="processBtn">Process result</button></div><div class="status" id="status">Border preview updates live.</div>`;
  else if(id==='image-watermark') controls=`<div class="wm-mode-tabs" role="tablist"><button type="button" class="active" id="wmAddTab">Add Watermark</button><button type="button" id="wmRemoveTab">Remove Watermark</button></div><div id="wmAddPanel">${textControls(true)}</div><div id="wmRemovePanel" hidden><div class="wm-authorized-note"><b>Remove a watermark from an image you own or are authorized to edit.</b></div><div class="btns"><button class="btn" type="button" id="wmAutoDetect">Detect Watermark</button><button class="btn-secondary" type="button" id="wmUndo">Undo</button><button class="btn-secondary" type="button" id="wmClear">Clear</button></div><details><summary>Refine selection</summary><div class="form-grid"><div class="field"><label>Tool</label><select id="wmMaskTool"><option value="brush">Mark watermark</option><option value="erase">Restore selection</option><option value="rect">Rectangle</option></select></div><div class="field"><label>Brush size</label><input id="wmBrush" type="range" min="6" max="160" value="42"></div></div></details><div hidden><input id="wmExpand" type="range" min="0" max="24" value="4"><input id="wmFeather" type="range" min="0" max="24" value="5"><select id="wmPreviewMode"><option value="result">Cleaned result</option></select><input id="wmCompare" type="range" min="0" max="100" value="100"><button type="button" id="wmRedo">Redo</button></div><div class="note">Start with Detect Watermark. Use Refine only if the automatic selection needs correction.</div></div><div class="form-grid">${formatSelect(true)}</div><div class="btns"><button class="btn" id="processBtn">Process result</button></div><div class="status" id="status">Add mode: drag the preview to position text. Remove mode: mark the watermark and refine the live result.</div>`;
  else if(id==='image-text') controls=`${textControls(false)}<div class="form-grid">${formatSelect(true)}</div><div class="btns"><button class="btn" id="processBtn">Process result</button></div><div class="status" id="status">Text position and style update live. Drag directly on the processed preview for custom placement.</div>`;
  else if(id==='image-exif') controls=`<div class="form-grid">${formatSelect(true)}</div><div class="btns"><button class="btn" id="processBtn">Process clean copy</button></div><div class="status" id="status">The re-exported image drops common EXIF metadata.</div>`;
  else if(id==='image-bg-remove') controls=`<div class="bg-auto-note"><b>Automatic transparent background</b><p>Remove the background, compare Before/After, then use Refine only when an edge needs correction.</p></div><div class="btns"><button class="btn" id="processBtn">Remove Background Automatically</button><button class="btn-secondary" id="bgResetBtn" type="button">Choose Another Image</button></div><div class="bg-refine" id="bgRefine" hidden><div class="form-grid"><div class="field"><label>Preview background</label><select id="bgPreviewMode"><option value="checker">Checker</option><option value="white">White</option><option value="dark">Dark</option></select></div><div class="field"><label>Brush</label><select id="bgBrushMode"><option value="erase">Erase</option><option value="restore">Restore</option></select></div><div class="field"><label>Brush size</label><input id="bgBrushSize" type="range" min="4" max="160" value="36"></div><div class="field"><label>Edge softness</label><input id="bgBrushSoft" type="range" min="0" max="100" value="35"></div></div><p class="note">Paint directly on the processed preview. Erase removes leftover background; Restore paints original pixels back. Full-resolution alpha is exported.</p></div><div class="status" id="status">Upload an image, then choose Remove Background. The download stays disabled until a nonblank PNG passes verification.</div>`;
  inner=editorWrap(controls);
 }
 $('toolRoot').innerHTML=pageShell(inner);
(function detectOutputCapabilities(){if(id!=='image-convert')return;const sel=$('format'),c=document.createElement('canvas');c.width=c.height=2;try{if(c.toDataURL('image/avif').startsWith('data:image/avif')){supportedOut.add('image/avif');const o=document.createElement('option');o.value='image/avif';o.textContent='AVIF';sel?.appendChild(o)}}catch{}const note=document.createElement('div');note.className='format-note';note.textContent='TIFF and HEIC/HEIF inputs use lazy local decoders when needed. BMP/TIFF/ICO/HEIC outputs stay hidden because this build has no verified browser encoder for them; DoKitly does not fake those conversions.';sel?.parentElement?.appendChild(note)})();
}
render();
if(id==='image-convert'&&$('fileInput'))$('fileInput').accept='image/*,.tif,.tiff,.heic,.heif';

const needsSeparateDownload=!['image-info','image-color','print-size','image-base64','base64-image','image-target'].includes(id);
if(needsSeparateDownload&&$('processBtn')){const b=document.createElement('button');b.type='button';b.id='finalImageDownload';b.className='btn-secondary';b.disabled=true;b.textContent=id==='multi-resize'||id==='multi-compress'?'Download ZIP':'Download processed file';$('processBtn').parentElement.appendChild(b)}

let batchCancelled=false,batchFailed=[];let currentFile=null,currentImg=null,beforeURL=null,afterURL=null,lastPreviewCanvas=null,verifiedBlobURL=null,bgEditCanvas=null,bgPointer=null,cropState=null,cropRatio=null,previewRAF=0,previewSeq=0,targetResultBlob=null,targetResultType=null,preparedResultBlob=null,preparedResultType=null,preparedResultName=null,batchZipBlob=null;
let wmMode='add',wmMask=null,wmHistory=[],wmRedoStack=[],wmRectStart=null,wmPaint=false,wmLiveTimer=0;
function setStatus(msg,strong=''){if($('status'))$('status').innerHTML=strong?`<strong>${esc(strong)}</strong> ${esc(msg)}`:esc(msg)}
function selectedType(forceTransparent=false){return typeFor(currentFile,$('format')?.value||'same',forceTransparent)}
function quality(){return Number($('quality')?.value||92)/100}
function showBefore(file,img,url){currentFile=file;currentImg=img;preparedResultBlob=null;batchZipBlob=null;if($('finalImageDownload'))$('finalImageDownload').disabled=true;if(id==='image-target'){targetResultBlob=null;targetResultType=null;if($('targetDownloadBtn'))$('targetDownloadBtn').disabled=true;}if(beforeURL&&beforeURL!==url)URL.revokeObjectURL(beforeURL);beforeURL=url;const name=$('uploadName');if(name){name.textContent=file.name;name.title=file.name}const stage=$('beforeStage');if(stage){stage.innerHTML=`<img id="beforeImg" src="${url}" alt="${esc(file.name)}">`;stage.title=file.name}if($('beforeMeta'))$('beforeMeta').textContent=`${img.width} × ${img.height} • ${humanSize(file.size)}`;document.querySelector('[data-zoom="before"]')?.removeAttribute('hidden')}
function previewSource(maxSide=900){if(!currentImg)return null;const scale=Math.min(1,maxSide/Math.max(currentImg.width,currentImg.height));return {img:currentImg,w:Math.max(1,Math.round(currentImg.width*scale)),h:Math.max(1,Math.round(currentImg.height*scale)),scale}}
function fitPreviewMedia(stage=$('afterStage')){
 if(!stage)return;
 const media=stage.querySelector('canvas,img');
 if(!media)return;
 const apply=()=>{
  const cs=getComputedStyle(stage),boxW=Math.max(1,stage.clientWidth-parseFloat(cs.paddingLeft||0)-parseFloat(cs.paddingRight||0)),boxH=Math.max(1,stage.clientHeight-parseFloat(cs.paddingTop||0)-parseFloat(cs.paddingBottom||0));
  const srcW=media.tagName==='CANVAS'?media.width:media.naturalWidth,srcH=media.tagName==='CANVAS'?media.height:media.naturalHeight;
  if(!srcW||!srcH)return;
  const scale=Math.min(boxW/srcW,boxH/srcH),w=Math.max(1,Math.floor(srcW*scale)),h=Math.max(1,Math.floor(srcH*scale));
  media.style.setProperty('width',w+'px','important');media.style.setProperty('height',h+'px','important');media.style.setProperty('max-width','none','important');media.style.setProperty('max-height','none','important');media.style.setProperty('object-fit','contain','important');media.style.setProperty('display','block','important');media.style.setProperty('margin','auto','important');
 };
 if(media.tagName==='IMG'&&!media.complete)media.addEventListener('load',apply,{once:true});else apply();
}
function showCanvasPreview(c,meta=''){lastPreviewCanvas=c;const stage=$('afterStage');if(!stage)return;stage.innerHTML='';stage.appendChild(c);c.classList.add('preview-canvas');fitPreviewMedia(stage);requestAnimationFrame(()=>fitPreviewMedia(stage));if($('afterMeta'))$('afterMeta').textContent=meta||`${c.width} × ${c.height}`;document.querySelector('[data-zoom="after"]')?.removeAttribute('hidden')}
function showCompareSlider(c){if(!beforeURL||!c||!['image-bg-remove','image-watermark'].includes(id))return;const stage=$('afterStage');if(!stage)return;const wrap=document.createElement('div');wrap.className='dk33-compare';const before=document.createElement('img');before.src=beforeURL;before.alt='Before';const after=document.createElement('div');after.className='dk33-after';const clone=document.createElement('canvas');clone.width=c.width;clone.height=c.height;clone.getContext('2d').drawImage(c,0,0);after.appendChild(clone);const lb=document.createElement('span');lb.className='dk33-compare-label before';lb.textContent='Before';const la=document.createElement('span');la.className='dk33-compare-label after';la.textContent='After';const range=document.createElement('input');range.type='range';range.min=0;range.max=100;range.value=50;range.setAttribute('aria-label','Compare before and after');range.oninput=()=>after.style.width=range.value+'%';wrap.append(before,after,lb,la,range);stage.innerHTML='';stage.appendChild(wrap)}
async function triggerDownload(blob,name){if(window.DoKitlyDownload?.routeBlob){await window.DoKitlyDownload.routeBlob(blob,{filename:name,mimeType:blob.type,tool:id});return}if(afterURL)URL.revokeObjectURL(afterURL);afterURL=URL.createObjectURL(blob);const a=document.createElement('a');a.href=afterURL;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>{if(afterURL){URL.revokeObjectURL(afterURL);afterURL=null}},4000)}
function positionXY(ctx,txt,size,pos,w,h,ox=0,oy=0){const m=ctx.measureText(txt),pad=Math.max(8,Math.round(Math.min(w,h)*.025));let x=(w-m.width)/2,y=(h-size)/2;if(pos[0]==='t')y=pad;if(pos[0]==='b')y=h-size-pad;if(pos[1]==='l')x=pad;if(pos[1]==='r')x=w-m.width-pad;if(pos==='custom'){x=w/2-m.width/2+(ox/100)*(w/2);y=h/2-size/2+(oy/100)*(h/2)}return{x,y,m}}
function applySharpen(c,amount){if(amount<=0)return c;const ctx=c.getContext('2d',{willReadFrequently:true}),src=ctx.getImageData(0,0,c.width,c.height),out=ctx.createImageData(c.width,c.height),sd=src.data,od=out.data,w=c.width,h=c.height,amt=Math.min(1,amount/100);od.set(sd);for(let y=1;y<h-1;y++){for(let x=1;x<w-1;x++){const p=(y*w+x)*4;for(let ch=0;ch<3;ch++){const sharp=5*sd[p+ch]-sd[p-4+ch]-sd[p+4+ch]-sd[p-w*4+ch]-sd[p+w*4+ch];od[p+ch]=Math.max(0,Math.min(255,sd[p+ch]*(1-amt)+sharp*amt))}od[p+3]=sd[p+3]}}ctx.putImageData(out,0,0);return c}
function adjustmentFilter(){const v=n=>Number($('adj-'+n)?.value||0),brightness=(100+v('brightness'))*(100+v('exposure'))/100,sat=(100+v('saturate'))*(100+v('vibrance'))/100;return{filter:`brightness(${Math.max(0,brightness)}%) contrast(${Math.max(0,100+v('contrast'))}%) saturate(${Math.max(0,sat)}%) hue-rotate(${v('hue')}deg) blur(${v('blur')}px) sepia(${v('sepia')}%) grayscale(${v('grayscale')}%) opacity(${Math.max(10,100+v('opacity'))}%)`,warmth:v('warmth'),tint:v('tint'),highlights:v('highlights'),shadows:v('shadows'),sharpen:v('sharpen')}}
function drawVisual(full=false){if(!currentImg)return null;const src=full?{w:currentImg.width,h:currentImg.height,scale:1}:previewSource(id==='image-filter'?600:900);let type=selectedType(id==='image-bg-remove'),c,ctx;
 if(id==='image-crop'){if(!cropState)return null;const s=cropState,sx=s.imgW/s.dispW,sy=s.imgH/s.dispH,fx=Math.round(s.x*sx),fy=Math.round(s.y*sy),fw=Math.max(1,Math.round(s.w*sx)),fh=Math.max(1,Math.round(s.h*sy)),scale=full?1:Math.min(1,900/Math.max(fw,fh));c=document.createElement('canvas');c.width=Math.max(1,Math.round(fw*scale));c.height=Math.max(1,Math.round(fh*scale));c.getContext('2d').drawImage(currentImg,fx,fy,fw,fh,0,0,c.width,c.height);return c}
 if(id==='image-compress'){let w=Number($('width')?.value)||currentImg.width,h=Number($('height')?.value)||currentImg.height;if(Number($('width')?.value)&&!Number($('height')?.value))h=currentImg.height*w/currentImg.width;if(Number($('height')?.value)&&!Number($('width')?.value))w=currentImg.width*h/currentImg.height;if(!full){const sc=Math.min(1,900/Math.max(w,h));w*=sc;h*=sc}return canvasDraw(currentImg,w,h,type)}
 if(id==='multi-resize'){let w=currentImg.width,h=currentImg.height,mw=Number($('batchWidth')?.value)||1200;if(w>mw){h*=mw/w;w=mw}if(!full){const sc=Math.min(1,900/Math.max(w,h));w*=sc;h*=sc}return canvasDraw(currentImg,w,h,type)}
 if(id==='image-resize'){const pct=Math.max(.01,Number($('resizePercent')?.value||100)/100),rawW=Number($('width')?.value),rawH=Number($('height')?.value);let w=rawW||currentImg.width*pct,h=rawH||currentImg.height*pct;if($('lockRatio')?.checked){if(rawW&&!rawH)h=currentImg.height*w/currentImg.width;else if(rawH&&!rawW)w=currentImg.width*h/currentImg.height;else if(rawW&&rawH){const fit=$('resizeFit')?.value||'stretch',r=fit==='cover'?Math.max(w/currentImg.width,h/currentImg.height):Math.min(w/currentImg.width,h/currentImg.height);if(fit!=='stretch'){const tw=w,th=h,sw=currentImg.width*r,sh=currentImg.height*r,c=document.createElement('canvas');c.width=Math.max(1,Math.round(tw));c.height=Math.max(1,Math.round(th));const x=c.getContext('2d');if(type==='image/jpeg'){x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height)}x.drawImage(currentImg,(tw-sw)/2,(th-sh)/2,sw,sh);if(!full&&Math.max(c.width,c.height)>900){const q=canvasDraw(c,c.width*Math.min(1,900/Math.max(c.width,c.height)),c.height*Math.min(1,900/Math.max(c.width,c.height)),type);c.width=c.height=1;return q}return c}}else h=currentImg.height*w/currentImg.width}h=h||currentImg.height;if(!full){const sc=Math.min(1,900/Math.max(w,h));w*=sc;h*=sc}return canvasDraw(currentImg,w,h,type)}
 if(id==='image-percent'){const p=Number($('percent')?.value||100)/100;let w=currentImg.width*p,h=currentImg.height*p;if(!full){const sc=Math.min(1,900/Math.max(w,h));w*=sc;h*=sc}return canvasDraw(currentImg,w,h,type)}
 if(id==='image-passport'){const[mw,mh]=($('passportPreset')?.value||'35,45').split(',').map(Number),dpi=Number($('dpi')?.value)||300;let w=mw/25.4*dpi,h=mh/25.4*dpi;if(!full){const sc=Math.min(1,900/Math.max(w,h));w*=sc;h*=sc}w=Math.max(1,Math.round(w));h=Math.max(1,Math.round(h));const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d'),zoom=(Number($('passportZoom')?.value)||110)/100,ox=(Number($('passportX')?.value)||0)/100*w*.45,oy=(Number($('passportY')?.value)||0)/100*h*.45,sc=Math.max(w/currentImg.width,h/currentImg.height)*zoom,dw=currentImg.width*sc,dh=currentImg.height*sc;x.fillStyle='#fff';x.fillRect(0,0,w,h);x.drawImage(currentImg,(w-dw)/2+ox,(h-dh)/2+oy,dw,dh);return c}
 if(id==='image-rotate'){const deg=Number($('rotate')?.value||0),swap=deg%180!==0,w0=src.w,h0=src.h;c=document.createElement('canvas');c.width=swap?h0:w0;c.height=swap?w0:h0;ctx=c.getContext('2d');if(type==='image/jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height)}ctx.translate(c.width/2,c.height/2);ctx.rotate(deg*Math.PI/180);const f=$('flip')?.value||'none';ctx.scale(f==='h'?-1:1,f==='v'?-1:1);ctx.drawImage(currentImg,-w0/2,-h0/2,w0,h0);return c}
 c=canvasDraw(currentImg,src.w,src.h,type);ctx=c.getContext('2d',{willReadFrequently:true});
 if(id==='image-filter'){ctx.clearRect(0,0,c.width,c.height);const a=adjustmentFilter();if(type==='image/jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height)}ctx.filter=a.filter;ctx.drawImage(currentImg,0,0,c.width,c.height);ctx.filter='none';if(a.warmth||a.tint){ctx.globalCompositeOperation='source-atop';if(a.warmth){ctx.globalAlpha=Math.min(.30,Math.abs(a.warmth)/300);ctx.fillStyle=a.warmth>0?'#ff8a32':'#3b82f6';ctx.fillRect(0,0,c.width,c.height)}if(a.tint){ctx.globalAlpha=Math.min(.24,Math.abs(a.tint)/340);ctx.fillStyle=a.tint>0?'#d946ef':'#22c55e';ctx.fillRect(0,0,c.width,c.height)}ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over'}if(a.highlights||a.shadows){const im=ctx.getImageData(0,0,c.width,c.height),d=im.data,hi=a.highlights/100,sh=a.shadows/100;for(let i=0;i<d.length;i+=4){const lum=(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2])/255,delta=hi*lum*lum*70+sh*(1-lum)*(1-lum)*70;d[i]=Math.max(0,Math.min(255,d[i]+delta));d[i+1]=Math.max(0,Math.min(255,d[i+1]+delta));d[i+2]=Math.max(0,Math.min(255,d[i+2]+delta))}ctx.putImageData(im,0,0)}if(a.sharpen)applySharpen(c,a.sharpen)}
 else if(id==='image-grayscale'){ctx.clearRect(0,0,c.width,c.height);ctx.filter=`grayscale(${Number($('simpleLive')?.value||0)}%)`;ctx.drawImage(currentImg,0,0,c.width,c.height);ctx.filter='none'}
 else if(id==='image-blur'){ctx.clearRect(0,0,c.width,c.height);ctx.filter=`blur(${Number($('simpleLive')?.value||0)}px)`;ctx.drawImage(currentImg,0,0,c.width,c.height);ctx.filter='none'}
 else if(id==='image-sharpen')applySharpen(c,Number($('sharpenAmount')?.value||0));
 else if(id==='image-border'){const bwRaw=Number($('borderW')?.value||0),bw=full?bwRaw:Math.round(bwRaw*src.scale),old=c;c=document.createElement('canvas');c.width=old.width+bw*2;c.height=old.height+bw*2;ctx=c.getContext('2d');ctx.fillStyle=$('borderColor')?.value||'#2563eb';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(old,bw,bw)}
 else if(id==='image-text'||(id==='image-watermark'&&wmMode==='add')){const txt=$('overlayText')?.value||'',sizeRaw=Number($('textSize')?.value||48),size=full?sizeRaw:Math.max(8,sizeRaw*src.scale),pos=$('position')?.value||'cc',opacity=Number($('opacity')?.value??100)/100,rot=Number($('rotation')?.value||0),ox=Number($('offsetX')?.value||0),oy=Number($('offsetY')?.value||0),style=$('fontStyle')?.value||'bold';ctx.save();ctx.globalAlpha=opacity;ctx.fillStyle=$('textColor')?.value||'#fff';ctx.font=`${style.includes('italic')?'italic ':''}${style.includes('bold')?'700':'400'} ${size}px system-ui`;ctx.textBaseline='top';const p=positionXY(ctx,txt,size,pos,c.width,c.height,ox,oy);ctx.translate(p.x+p.m.width/2,p.y+size/2);ctx.rotate(rot*Math.PI/180);ctx.fillText(txt,-p.m.width/2,-size/2);ctx.restore()}
 else if(id==='image-bg-remove'){/* Preview remains the original until automatic processing finishes. */}
 return c}
function schedulePreview(){if(!currentImg||['image-base64','image-info','image-color','base64-image','print-size'].includes(id))return;cancelAnimationFrame(previewRAF);const seq=++previewSeq;previewRAF=requestAnimationFrame(()=>{setTimeout(()=>{if(seq!==previewSeq)return;try{const c=drawVisual(false);if(c)showCanvasPreview(c,`${c.width} × ${c.height} preview`)}catch(e){setStatus(e.message)}},0)})}
async function handleFile(file){if(!file)return;const r=await readImage(file);showBefore(file,r.img,r.url);if(id==='image-crop')initCrop(r.img,r.url);if(id==='image-color')bindColorCanvas(r.img);if(id==='image-info')$('infoOut').innerHTML=`<strong>${esc(file.name)}</strong><br>${r.img.width} × ${r.img.height}px • ${esc(file.type||'unknown')} • ${humanSize(file.size)}`;if(id==='image-exif'){metadataSignals(file).then(a=>setStatus(a.length?`Detected metadata containers: ${a.join(', ')}. Process a clean copy to remove and verify them.`:'No common EXIF/XMP/IPTC metadata container detected; re-export can still normalize the image.','Metadata:')).catch(()=>{})}if(!['image-base64','image-info','image-color'].includes(id))schedulePreview()}
$('fileInput')?.addEventListener('change',e=>{const files=[...(e.target.files||[])];if(!files.length)return;const name=$('uploadName');if(name&&files.length>1){name.textContent=`${files.length} images selected`;name.title=files.map(f=>f.name).join(' • ')}if(id==='multi-resize'||id==='multi-compress'){handleFile(files[0]).then(()=>{if(name){name.textContent=`${files.length} images selected`;name.title=files.map(f=>f.name).join(' • ')}}).catch(err=>setStatus(err.message));return}handleFile(files[0]).catch(err=>setStatus(err.message))});

document.addEventListener('click',e=>{const z=e.target.closest('[data-zoom]');if(!z)return;const src=z.dataset.zoom==='before'?beforeURL:null;const m=document.createElement('div');m.className='preview-modal';m.innerHTML='<button class="preview-close" aria-label="Close">×</button>';if(src){const im=document.createElement('img');im.src=src;m.appendChild(im)}else if(lastPreviewCanvas){m.appendChild(lastPreviewCanvas.cloneNode(true));const c=m.querySelector('canvas');c.width=lastPreviewCanvas.width;c.height=lastPreviewCanvas.height;c.getContext('2d').drawImage(lastPreviewCanvas,0,0)}else return;document.body.appendChild(m);m.querySelector('button').onclick=()=>m.remove();m.onclick=ev=>{if(ev.target===m)m.remove()}});

function bindCropDrag(){const box=$('cropBox'),handle=$('cropHandle');if(!box||!handle)return;let mode=null,start=null,orig=null;const down=(e,m)=>{e.preventDefault();mode=m;start={x:e.clientX,y:e.clientY};orig={...cropState};box.setPointerCapture?.(e.pointerId)};box.onpointerdown=e=>{if(e.target===handle)return;down(e,'move')};handle.onpointerdown=e=>{e.stopPropagation();down(e,'resize')};box.onpointermove=e=>{if(!mode)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;if(mode==='move'){cropState.x=orig.x+dx;cropState.y=orig.y+dy}else{cropState.w=orig.w+dx;cropState.h=cropRatio?cropState.w/cropRatio:orig.h+dy}constrainCrop();paintCrop(true)};box.onpointerup=()=>{mode=null;paintCrop(true)};box.onpointercancel=()=>mode=null}
function constrainCrop(){const s=cropState;if(!s)return;s.w=Math.max(30,Math.min(s.w,s.dispW-s.x));s.h=Math.max(30,Math.min(s.h,s.dispH-s.y));s.x=Math.max(0,Math.min(s.x,s.dispW-s.w));s.y=Math.max(0,Math.min(s.y,s.dispH-s.h));if(cropRatio){let h=s.w/cropRatio;if(s.y+h<=s.dispH)s.h=h;else{s.h=s.dispH-s.y;s.w=s.h*cropRatio}}}
function paintCrop(update=true){if(!cropState)return;const b=$('cropBox'),s=cropState;if(!b)return;b.style.transform=`translate3d(${s.x}px,${s.y}px,0)`;b.style.width=s.w+'px';b.style.height=s.h+'px';const sx=s.imgW/s.dispW,sy=s.imgH/s.dispH;$('cropMeta').textContent=`${Math.round(s.x*sx)}, ${Math.round(s.y*sy)} • ${Math.round(s.w*sx)} × ${Math.round(s.h*sy)}px`;if(update)schedulePreview()}
function initCrop(img,url){const stage=$('cropStage');if(!stage)return;stage.innerHTML=`<div class="crop-wrap" id="cropWrap"><img id="cropImg" src="${url}" alt="Crop source"><div class="crop-box" id="cropBox"><span class="crop-handle" id="cropHandle"></span></div></div>`;const image=$('cropImg');const ready=()=>{const wr=image.clientWidth,hr=image.clientHeight;if(!wr||!hr)return;cropState={x:wr*.1,y:hr*.1,w:wr*.8,h:hr*.8,dispW:wr,dispH:hr,imgW:img.width,imgH:img.height};paintCrop(true);bindCropDrag()};image.onload=ready;if(image.complete)requestAnimationFrame(ready)}
if(id==='image-crop'){document.querySelectorAll('[data-ratio]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-ratio]').forEach(x=>x.classList.remove('active'));b.classList.add('active');cropRatio=b.dataset.ratio==='free'?null:Number(b.dataset.ratio);if(cropState&&cropRatio){cropState.h=cropState.w/cropRatio;constrainCrop();paintCrop(true)}})}

function bindRanges(){
 document.querySelectorAll('[data-ui-range]').forEach(el=>{const out=$('out-'+el.id),unit=el.dataset.unit||'',def=Number(el.value),isSigned=el.dataset.signed==='1';el.dataset.default=def;const refresh=()=>{if(out)out.textContent=isSigned?signedValue(el.value,unit):`${el.value}${unit}`;const card=el.closest('.control-card');card?.classList.toggle('changed',Number(el.value)!==def);schedulePreview()};el.addEventListener('input',refresh);el.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))requestAnimationFrame(refresh)});refresh()});
 document.querySelectorAll('[data-range-nudge]').forEach(btn=>btn.addEventListener('click',()=>{const[rid,deltaS]=btn.dataset.rangeNudge.split(':'),el=$(rid);if(!el)return;el.value=Math.max(Number(el.min),Math.min(Number(el.max),Number(el.value)+Number(deltaS)));el.dispatchEvent(new Event('input',{bubbles:true}));el.focus()}));
 document.querySelectorAll('[data-range-reset]').forEach(btn=>btn.addEventListener('click',()=>{const el=$(btn.dataset.rangeReset);if(!el)return;el.value=btn.dataset.default;el.dispatchEvent(new Event('input',{bubbles:true}));el.focus()}));
}
bindRanges();
if(id==='image-filter'){
 const defaults={brightness:0,contrast:0,saturate:0,exposure:0,highlights:0,shadows:0,warmth:0,tint:0,hue:0,vibrance:0,blur:0,sepia:0,grayscale:0,opacity:0,sharpen:0};
 const units={brightness:'',contrast:'',saturate:'',exposure:'',highlights:'',shadows:'',warmth:'',tint:'',hue:'°',vibrance:'',blur:'px',sepia:'',grayscale:'',opacity:'',sharpen:''};
 const update=el=>{const key=el.dataset.adj,out=$('out-'+key);if(out)out.textContent=signedValue(el.value,units[key]);el.closest('.control-card')?.classList.toggle('changed',Number(el.value)!==defaults[key]);schedulePreview()};
 document.querySelectorAll('[data-adj]').forEach(el=>{el.addEventListener('input',()=>update(el));el.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))requestAnimationFrame(()=>update(el))})});
 document.querySelectorAll('[data-reset-adj]').forEach(btn=>btn.onclick=()=>{const el=$('adj-'+btn.dataset.resetAdj);el.value=defaults[btn.dataset.resetAdj];el.dispatchEvent(new Event('input',{bubbles:true}))});
 document.querySelectorAll('[data-nudge]').forEach(btn=>btn.onclick=()=>{const[k,s]=btn.dataset.nudge.split(':'),el=$('adj-'+k);el.value=Math.max(Number(el.min),Math.min(Number(el.max),Number(el.value)+Number(s)));el.dispatchEvent(new Event('input',{bubbles:true}));el.focus()});
 const presets={auto:{brightness:4,contrast:6,saturate:6,exposure:1,highlights:2,shadows:4,vibrance:8},vivid:{brightness:3,contrast:12,saturate:28,exposure:1,vibrance:26},warm:{brightness:3,contrast:4,saturate:8,warmth:35,vibrance:8},cool:{brightness:2,contrast:5,saturate:3,warmth:-32,tint:-5},bw:{brightness:3,contrast:12,grayscale:100,saturate:-100,vibrance:-100}};
 const apply=vals=>document.querySelectorAll('[data-adj]').forEach(el=>{el.value=vals[el.dataset.adj]??0;update(el)});
 document.querySelectorAll('[data-preset]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-preset]').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');apply(presets[btn.dataset.preset]||{})});
 if($('resetBtn'))$('resetBtn').onclick=()=>{document.querySelectorAll('[data-preset]').forEach(x=>x.classList.remove('selected'));apply({})};
}
let adjustUndo=[],adjustRedo=[],adjustLock=false;
function adjustmentSnapshot(){const o={};document.querySelectorAll('[data-adj]').forEach(el=>o[el.dataset.adj]=el.value);return o}
function restoreAdjustmentSnapshot(o){if(!o)return;adjustLock=true;document.querySelectorAll('[data-adj]').forEach(el=>{if(o[el.dataset.adj]!=null){el.value=o[el.dataset.adj];el.dispatchEvent(new Event('input',{bubbles:true}))}});adjustLock=false;schedulePreview()}
function pushAdjustmentHistory(){if(id!=='image-filter'||adjustLock)return;const snap=adjustmentSnapshot(),last=adjustUndo[adjustUndo.length-1];if(last&&JSON.stringify(last)===JSON.stringify(snap))return;adjustUndo.push(snap);if(adjustUndo.length>40)adjustUndo.shift();adjustRedo=[]}
if(id==='image-filter'){setTimeout(()=>pushAdjustmentHistory(),0);document.querySelectorAll('[data-adj]').forEach(el=>el.addEventListener('change',pushAdjustmentHistory));$('undoAdjustBtn')?.addEventListener('click',()=>{if(adjustUndo.length<2)return;adjustRedo.push(adjustUndo.pop());restoreAdjustmentSnapshot(adjustUndo[adjustUndo.length-1])});$('redoAdjustBtn')?.addEventListener('click',()=>{const n=adjustRedo.pop();if(!n)return;adjustUndo.push(n);restoreAdjustmentSnapshot(n)})}
// Text/watermark direct manipulation: dragging the processed preview switches to custom position.
if(id==='image-text'||id==='image-watermark'){let drag=false;const stage=$('afterStage');stage?.addEventListener('pointerdown',e=>{if(!currentImg||(id==='image-watermark'&&wmMode!=='add'))return;drag=true;stage.setPointerCapture?.(e.pointerId);const move=ev=>{if(!drag)return;const r=stage.getBoundingClientRect(),x=((ev.clientX-r.left)/r.width*200-100),y=((ev.clientY-r.top)/r.height*200-100);$('position').value='custom';$('offsetX').value=Math.max(-100,Math.min(100,Math.round(x)));$('offsetY').value=Math.max(-100,Math.min(100,Math.round(y)));$('offsetX').dispatchEvent(new Event('input',{bubbles:true}));$('offsetY').dispatchEvent(new Event('input',{bubbles:true}))};move(e);const up=()=>{drag=false;stage.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};stage.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true})})}

function wmEnsureMask(){if(!currentImg)return null;const src=previewSource(900);if(!wmMask||wmMask.width!==src.w||wmMask.height!==src.h){wmMask=document.createElement('canvas');wmMask.width=src.w;wmMask.height=src.h;wmHistory=[];wmRedoStack=[]}return wmMask}
function wmSnapshot(){if(!wmMask)return;const x=wmMask.getContext('2d'),d=x.getImageData(0,0,wmMask.width,wmMask.height);wmHistory.push(d);if(wmHistory.length>30)wmHistory.shift();wmRedoStack=[]}
function wmRestore(d){if(!d||!wmMask)return;wmMask.getContext('2d').putImageData(d,0,0);wmScheduleLive()}
function wmExpandedMask(targetW,targetH){const m=wmEnsureMask(),out=document.createElement('canvas');out.width=targetW;out.height=targetH;const x=out.getContext('2d');x.drawImage(m,0,0,targetW,targetH);const expand=Number($('wmExpand')?.value||0)*targetW/m.width,feather=Number($('wmFeather')?.value||0)*targetW/m.width;if(expand>0){const base=document.createElement('canvas');base.width=targetW;base.height=targetH;base.getContext('2d').drawImage(out,0,0);x.globalCompositeOperation='source-over';for(let a=0;a<Math.PI*2;a+=Math.PI/8)x.drawImage(base,Math.cos(a)*expand,Math.sin(a)*expand)}if(feather>0){const base=document.createElement('canvas');base.width=targetW;base.height=targetH;base.getContext('2d').drawImage(out,0,0);x.clearRect(0,0,targetW,targetH);x.filter=`blur(${Math.min(30,feather)}px)`;x.drawImage(base,0,0);x.filter='none'}return out}
function wmBuildResult(full=false){
 if(!currentImg)return null;
 const src=full?{w:currentImg.width,h:currentImg.height}:previewSource(900),base=canvasDraw(currentImg,src.w,src.h,selectedType(false)),mask=wmExpandedMask(src.w,src.h),ctx=base.getContext('2d'),md=mask.getContext('2d',{willReadFrequently:true}).getImageData(0,0,src.w,src.h).data;
 if(!$('wmMaskTool'))return base;
 const image=ctx.getImageData(0,0,src.w,src.h),d=image.data,out=new Uint8ClampedArray(d),known=new Uint8Array(src.w*src.h),queued=new Uint8Array(src.w*src.h),queue=new Int32Array(src.w*src.h);let head=0,tail=0;
 for(let p=0;p<known.length;p++)if(md[p*4+3]<20)known[p]=1;
 const enqueueBoundary=p=>{if(known[p]||queued[p])return;const x=p%src.w,y=(p/src.w)|0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){if(!dx&&!dy)continue;const xx=x+dx,yy=y+dy;if(xx>=0&&yy>=0&&xx<src.w&&yy<src.h&&known[yy*src.w+xx]){queued[p]=1;queue[tail++]=p;return}}};
 for(let p=0;p<known.length;p++)if(!known[p])enqueueBoundary(p);
 // Build 31: linear-time boundary propagation. Each masked pixel is reconstructed once
 // from already reconstructed/real neighbours, avoiding the previous flat 8-point smear.
 while(head<tail){const p=queue[head++],x=p%src.w,y=(p/src.w)|0;let rr=0,gg=0,bb=0,aa=0,wt=0;for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){if(!dx&&!dy)continue;const xx=x+dx,yy=y+dy;if(xx<0||yy<0||xx>=src.w||yy>=src.h)continue;const q=yy*src.w+xx;if(!known[q])continue;const w=1/Math.max(1,Math.hypot(dx,dy)),j=q*4;rr+=out[j]*w;gg+=out[j+1]*w;bb+=out[j+2]*w;aa+=out[j+3]*w;wt+=w}if(wt){const i=p*4;out[i]=rr/wt;out[i+1]=gg/wt;out[i+2]=bb/wt;out[i+3]=aa/wt}known[p]=1;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const xx=x+dx,yy=y+dy;if(xx<0||yy<0||xx>=src.w||yy>=src.h)continue;enqueueBoundary(yy*src.w+xx)}}
 // Blend feathered boundary with the original according to mask strength.
 for(let p=0;p<known.length;p++){const a=md[p*4+3]/255;if(a<=0||a>=.98)continue;const i=p*4;for(let c=0;c<4;c++)out[i+c]=Math.round(d[i+c]*(1-a)+out[i+c]*a)}
 ctx.putImageData(new ImageData(out,src.w,src.h),0,0);return base;
}
function wmAutoDetect(){if(!currentImg)return setStatus('Select an image first.');const m=wmEnsureMask(),src=previewSource(900),c=canvasDraw(currentImg,src.w,src.h),x=c.getContext('2d',{willReadFrequently:true}),d=x.getImageData(0,0,c.width,c.height).data,mx=m.getContext('2d');mx.clearRect(0,0,m.width,m.height);const im=mx.createImageData(m.width,m.height),o=im.data;let hits=0;for(let y=1;y<m.height-1;y++)for(let xx=1;xx<m.width-1;xx++){const i=(y*m.width+xx)*4,l=.299*d[i]+.587*d[i+1]+.114*d[i+2],ir=(y*m.width+xx+1)*4,idn=((y+1)*m.width+xx)*4,lr=.299*d[ir]+.587*d[ir+1]+.114*d[ir+2],ld=.299*d[idn]+.587*d[idn+1]+.114*d[idn+2],edge=Math.abs(l-lr)+Math.abs(l-ld),sat=Math.max(d[i],d[i+1],d[i+2])-Math.min(d[i],d[i+1],d[i+2]);if(edge>62&&sat<72){o[i]=o[i+1]=o[i+2]=255;o[i+3]=190;hits++}}mx.putImageData(im,0,0);mx.filter='blur(1.4px)';mx.globalCompositeOperation='source-over';mx.drawImage(m,0,0);mx.filter='none';wmSnapshot();wmScheduleLive();setStatus(hits?`Auto Detect suggested ${hits.toLocaleString()} edge pixels. Refine the red mask; false positives are normal.`:'No confident overlay-like edges found. Paint the watermark manually.','Detect:')}
function wmBindEditor(){if(id!=='image-watermark')return;const add=$('wmAddTab'),rem=$('wmRemoveTab'),ap=$('wmAddPanel'),rp=$('wmRemovePanel');const setMode=m=>{wmMode=m;add?.classList.toggle('active',m==='add');rem?.classList.toggle('active',m==='remove');if(ap)ap.hidden=m!=='add';if(rp)rp.hidden=m!=='remove';preparedResultBlob=null;if($('finalImageDownload'))$('finalImageDownload').disabled=true;if(m==='remove'){wmEnsureMask();if(!wmHistory.length)wmSnapshot();wmScheduleLive();setStatus('Paint or Auto Detect the watermark, refine the mask, then process the full-resolution result.')}else schedulePreview()};add?.addEventListener('click',()=>setMode('add'));rem?.addEventListener('click',()=>setMode('remove'));$('wmAutoDetect')?.addEventListener('click',wmAutoDetect);$('wmClear')?.addEventListener('click',()=>{if(!wmEnsureMask())return;wmMask.getContext('2d').clearRect(0,0,wmMask.width,wmMask.height);wmSnapshot();wmScheduleLive()});$('wmUndo')?.addEventListener('click',()=>{if(wmHistory.length<2)return;wmRedoStack.push(wmHistory.pop());wmRestore(wmHistory[wmHistory.length-1])});$('wmRedo')?.addEventListener('click',()=>{const d=wmRedoStack.pop();if(!d)return;wmHistory.push(d);wmRestore(d)});['wmExpand','wmFeather','wmPreviewMode','wmCompare'].forEach(k=>{$(k)?.addEventListener('input',wmScheduleLive);$(k)?.addEventListener('change',wmScheduleLive)});const stage=$('afterStage');stage?.addEventListener('pointerdown',e=>{if(wmMode!=='remove'||!currentImg)return;const m=wmEnsureMask();wmPaint=true;const tool=$('wmMaskTool')?.value||'brush',r=stage.getBoundingClientRect(),point=ev=>({x:(ev.clientX-r.left)*m.width/r.width,y:(ev.clientY-r.top)*m.height/r.height});wmRectStart=point(e);const paint=ev=>{if(!wmPaint)return;const p=point(ev),x=m.getContext('2d'),size=Number($('wmBrush')?.value||42)*m.width/r.width;x.save();if(tool==='erase')x.globalCompositeOperation='destination-out';else x.globalCompositeOperation='source-over';x.fillStyle='#fff';if(tool==='rect'){x.restore();return}x.beginPath();x.arc(p.x,p.y,Math.max(2,size/2),0,Math.PI*2);x.fill();x.restore();wmScheduleLive()};paint(e);const up=ev=>{if(!wmPaint)return;wmPaint=false;if(tool==='rect'){const p=point(ev),x=m.getContext('2d');x.fillStyle='#fff';x.fillRect(Math.min(p.x,wmRectStart.x),Math.min(p.y,wmRectStart.y),Math.abs(p.x-wmRectStart.x),Math.abs(p.y-wmRectStart.y));wmScheduleLive()}wmSnapshot();stage.removeEventListener('pointermove',paint)};stage.addEventListener('pointermove',paint);window.addEventListener('pointerup',up,{once:true})});setMode('add')}
wmBindEditor();
const liveControlIds=['format','rotate','flip','width','height','lockRatio','resizePercent','resizeFit','targetKB','targetSelect','targetCustom','passportPreset','dpi','passportBg','passportTargetKB','passportZoom','passportX','passportY','borderW','borderColor','overlayText','textSize','textColor','position','fontStyle','batchWidth'];
liveControlIds.forEach(k=>{$(k)?.addEventListener('input',schedulePreview);$(k)?.addEventListener('change',schedulePreview)});
function updateUpscaleNote(){if(id!=='image-resize'||!currentImg)return;const w=Number($('width')?.value)||currentImg.width*Number($('resizePercent')?.value||100)/100,h=Number($('height')?.value)||currentImg.height*Number($('resizePercent')?.value||100)/100;const n=$('upscaleNote');if(n)n.textContent=(w>currentImg.width||h>currentImg.height)?'Upscaling enlarges pixels; it cannot recreate missing detail.':''}
['width','height','resizePercent'].forEach(k=>$(k)?.addEventListener('input',updateUpscaleNote));

async function compressToKB(targetKB,type,full=true){if(!currentImg)throw Error('Please select an image first.');const limit=targetKB*1024;if(limit<500)throw Error('Target size is too small.');let scale=1,best=null,bestCanvas=null;for(let pass=0;pass<12;pass++){const w=Math.max(1,Math.round(currentImg.width*scale)),h=Math.max(1,Math.round(currentImg.height*scale)),c=canvasDraw(currentImg,w,h,type);if(type==='image/png'){const b=await blobFromCanvas(c,type);if(b.size<=limit)return{blob:b,canvas:c};best=b;bestCanvas=c}else{let lo=.02,hi=.98,hit=null;for(let i=0;i<12;i++){const q=(lo+hi)/2,b=await blobFromCanvas(c,type,q);if(b.size<=limit){hit=b;lo=q}else hi=q}if(hit)return{blob:hit,canvas:c};const low=await blobFromCanvas(c,type,.02);best=low;bestCanvas=c}scale*=.86;if(Math.min(currentImg.width*scale,currentImg.height*scale)<40)break}return{blob:best,canvas:bestCanvas,miss:true}}
let selfieSegmenter=null;
async function personMaskCanvas(source){
 if(!window.SelfieSegmentation)throw Error('Optional portrait segmenter unavailable.');
 if(!selfieSegmenter){
  selfieSegmenter=new SelfieSegmentation({locateFile:f=>`https://cdn.jsdelivr.net/npm/@mediapipe/selfie_segmentation@0.1.1675465747/${f}`});
  selfieSegmenter.setOptions({modelSelection:1});
 }
 return new Promise((resolve,reject)=>{
  let finished=false;let timer=setTimeout(()=>{if(!finished){finished=true;reject(Error('Portrait segmentation timed out.'));}},15000);
  selfieSegmenter.onResults(r=>{
   if(finished)return;finished=true;clearTimeout(timer);
   try{
    const out=document.createElement('canvas');out.width=source.width;out.height=source.height;
    const x=out.getContext('2d',{willReadFrequently:true});x.drawImage(r.segmentationMask,0,0,out.width,out.height);
    const d=x.getImageData(0,0,out.width,out.height),a=d.data;
    let alphaLow=255,alphaHigh=0,colorLow=255,colorHigh=0;
    for(let i=0;i<a.length;i+=32){alphaLow=Math.min(alphaLow,a[i+3]);alphaHigh=Math.max(alphaHigh,a[i+3]);colorLow=Math.min(colorLow,a[i]);colorHigh=Math.max(colorHigh,a[i]);}
    const useAlpha=(alphaHigh-alphaLow)>24;
    for(let i=0;i<a.length;i+=4){const v=useAlpha?a[i+3]:(.3*a[i]+.59*a[i+1]+.11*a[i+2]);a[i]=a[i+1]=a[i+2]=255;a[i+3]=Math.round(v);}
    x.putImageData(d,0,0);resolve(out);
   }catch(e){reject(e)}
  });
  Promise.resolve().then(()=>selfieSegmenter.send({image:source})).catch(e=>{if(!finished){finished=true;clearTimeout(timer);reject(e)}});
 });
}
function canvasAlphaStats(c){
 const t=document.createElement('canvas');t.width=60;t.height=60;
 const x=t.getContext('2d',{willReadFrequently:true});x.drawImage(c,0,0,60,60);
 const d=x.getImageData(0,0,60,60).data;let visible=0,clear=0;
 for(let i=3;i<d.length;i+=4){if(d[i]>24)visible++;if(d[i]<225)clear++;}
 return{visible:visible/3600,clear:clear/3600};
}
function sampleBorderColor(source){
 const w=64,h=Math.max(24,Math.round(64*source.height/source.width)),c=canvasDraw(source,w,h),x=c.getContext('2d',{willReadFrequently:true}),d=x.getImageData(0,0,w,h).data,vals=[[],[],[]];
 const add=i=>{if(d[i+3]<16)return;vals[0].push(d[i]);vals[1].push(d[i+1]);vals[2].push(d[i+2])};
 for(let xx=0;xx<w;xx+=2){add(xx*4);add(((h-1)*w+xx)*4)}for(let yy=1;yy<h-1;yy+=2){add((yy*w)*4);add((yy*w+w-1)*4)}
 const med=a=>{a.sort((a,b)=>a-b);return a.length?a[Math.floor(a.length/2)]:255};
 const bg=vals.map(med),spread=Math.max(...vals.map((a,k)=>a.length?Math.max(...a.map(v=>Math.abs(v-bg[k]))):255));return{bg,spread};
}
function refineAlphaMask(mask){
 const out=document.createElement('canvas');out.width=mask.width;out.height=mask.height;const x=out.getContext('2d',{willReadFrequently:true});
 x.filter='blur(0.75px)';x.drawImage(mask,0,0);x.filter='none';const im=x.getImageData(0,0,out.width,out.height),a=im.data;
 for(let i=0;i<a.length;i+=4){let v=a[i+3]/255;v=Math.max(0,Math.min(1,(v-.035)/.93));v=v*v*(3-2*v);a[i]=a[i+1]=a[i+2]=255;a[i+3]=Math.round(v*255)}x.putImageData(im,0,0);return out;
}
function decontaminateEdges(out,source){
 const sample=sampleBorderColor(source);if(sample.spread>62)return out;const bg=sample.bg,x=out.getContext('2d',{willReadFrequently:true}),im=x.getImageData(0,0,out.width,out.height),d=im.data;
 for(let i=0;i<d.length;i+=4){const a=d[i+3]/255;if(a<=.06||a>=.97)continue;const strength=Math.min(.72,Math.max(0,(1-a)*.9));for(let k=0;k<3;k++){const est=(d[i+k]-bg[k]*(1-a))/Math.max(a,.08),cl=Math.max(0,Math.min(255,est));d[i+k]=Math.round(d[i+k]*(1-strength)+cl*strength)}}x.putImageData(im,0,0);return out;
}
function applyAlphaMask(source,mask){
 const out=canvasDraw(source,source.width,source.height,'image/png'),x=out.getContext('2d'),refined=refineAlphaMask(mask);
 x.globalCompositeOperation='destination-in';x.drawImage(refined,0,0,out.width,out.height);x.globalCompositeOperation='source-over';return decontaminateEdges(out,source);
}
// Automatic edge-connected background removal for plain/near-uniform photo backgrounds.
// Never infer foreground by deleting all pixels of a color: only pixels connected to the canvas border are removed.
function removeOuterBackground(source){
 const max=720,sc=Math.min(1,max/Math.max(source.width,source.height));
 const w=Math.max(1,Math.round(source.width*sc)),h=Math.max(1,Math.round(source.height*sc));
 const small=canvasDraw(source,w,h),x=small.getContext('2d',{willReadFrequently:true}),d=x.getImageData(0,0,w,h).data;
 const coords=[[1,1],[w-2,1],[1,h-2],[w-2,h-2]].map(([xx,yy])=>Math.max(0,Math.min(w-1,yy))*w+Math.max(0,Math.min(w-1,xx)));
 const samples=coords.map(i=>[d[i*4],d[i*4+1],d[i*4+2]]);
 const bg=[0,1,2].map(k=>samples.map(a=>a[k]).sort((a,b)=>a-b)[2]);
 const dist=(i)=>{let sum=0;for(let ch=0;ch<3;ch++){const a=d[i*4+ch]-bg[ch];sum+=a*a;}return Math.sqrt(sum);};
 const spread=Math.max(...coords.map(dist));
 if(spread>72)throw Error('The outer background is complex or varies strongly. Try a clearer subject/portrait; no blank image was created.');
 const tol=Math.min(78,Math.max(30,30+spread*.8));
 const seen=new Uint8Array(w*h),queue=new Int32Array(w*h);let front=0,back=0;
 function add(i){if(i<0||i>=seen.length||seen[i]||d[i*4+3]<25)return;if(dist(i)>tol)return;seen[i]=1;queue[back++]=i;}
 for(let j=0;j<w;j++){add(j);add((h-1)*w+j)}
 for(let j=0;j<h;j++){add(j*w);add(j*w+w-1)}
 while(front<back){const i=queue[front++],xx=i%w; if(xx>0)add(i-1);if(xx<w-1)add(i+1);add(i-w);add(i+w);}
 const removed=back/(w*h);if(removed<.015||removed>.98)throw Error('A safe foreground/background separation could not be identified. Your original image was not replaced.');
 const m=document.createElement('canvas');m.width=w;m.height=h;const mx=m.getContext('2d'),v=mx.createImageData(w,h);
 for(let i=0;i<seen.length;i++){v.data[i*4]=v.data[i*4+1]=v.data[i*4+2]=255;v.data[i*4+3]=seen[i]?0:255;}
 mx.putImageData(v,0,0);return applyAlphaMask(source,m);
}
async function autoRemoveBackground(source){
 let out=null,method='Edge-aware local removal',localError=null;
 // Build 33: do not ship an unverified third-party model path. Prefer foreground-safe
 // border-connected removal, then the established portrait segmenter when available.
 try{out=removeOuterBackground(source)}catch(e){localError=e}
 if(!out&&window.SelfieSegmentation){
  try{const mask=await personMaskCanvas(source),st=canvasAlphaStats(mask);
   if(st.visible>.018&&st.visible<.94&&st.clear>.03){out=applyAlphaMask(source,mask);method='Portrait segmentation + edge refinement';}}
  catch(e){console.info('Portrait segmenter unavailable:',e?.message||e);}
 }
 if(!out)throw(localError||Error('A reliable foreground/background separation could not be identified.'));
 const st=canvasAlphaStats(out);
 if(st.visible<.015||st.clear<.012)throw Error('The result would be empty or its background was not removed. No download was generated.');
 return{canvas:decontaminateEdges(out,source),method};
}
async function removePersonBackground(source,bg=null){const mask=await personMaskCanvas(source);const st=canvasAlphaStats(mask);if(st.visible<.015||st.visible>.98)throw Error('No reliable person mask found.');const out=applyAlphaMask(source,mask);if(bg){const x=out.getContext('2d');x.globalCompositeOperation='destination-over';x.fillStyle=bg;x.fillRect(0,0,out.width,out.height);x.globalCompositeOperation='source-over';}return out;}
function bindBgEditor(c){
 bgEditCanvas=c;$('bgRefine')?.removeAttribute('hidden');showCanvasPreview(c,`${c.width} × ${c.height} • manual refine ready`);
 const stage=$('afterStage');if(!stage)return;c.style.touchAction='none';c.style.cursor='crosshair';
 const paint=e=>{if(!bgPointer)return;const r=c.getBoundingClientRect(),px=(e.clientX-r.left)*c.width/r.width,py=(e.clientY-r.top)*c.height/r.height,size=Number($('bgBrushSize')?.value||36)*c.width/Math.max(1,r.width),soft=Number($('bgBrushSoft')?.value||35)/100,mode=$('bgBrushMode')?.value||'erase',x=c.getContext('2d');x.save();x.globalCompositeOperation=mode==='erase'?'destination-out':'source-over';const g=x.createRadialGradient(px,py,size*soft*.5,px,py,size/2);g.addColorStop(0,'rgba(0,0,0,1)');g.addColorStop(1,'rgba(0,0,0,0)');if(mode==='erase'){x.fillStyle=g;x.beginPath();x.arc(px,py,size/2,0,Math.PI*2);x.fill()}else if(currentImg){x.globalCompositeOperation='source-over';x.beginPath();x.arc(px,py,size/2,0,Math.PI*2);x.clip();x.globalAlpha=Math.max(.2,1-soft*.55);x.drawImage(currentImg,0,0,c.width,c.height)}x.restore();preparedResultBlob=null;updateBgBlob()};
 c.onpointerdown=e=>{bgPointer=e.pointerId;c.setPointerCapture?.(e.pointerId);paint(e)};c.onpointermove=paint;c.onpointerup=c.onpointercancel=()=>bgPointer=null;applyBgPreviewMode();
}
function applyBgPreviewMode(){const stage=$('afterStage');if(!stage)return;stage.dataset.bgPreview=$('bgPreviewMode')?.value||'checker'}
let bgBlobTimer=0;function updateBgBlob(){clearTimeout(bgBlobTimer);bgBlobTimer=setTimeout(async()=>{if(!bgEditCanvas)return;const b=await blobFromCanvas(bgEditCanvas,'image/png');preparedResultBlob=b;preparedResultType='image/png';preparedResultName=outName('image-bg-remove','image/png');if($('afterMeta'))$('afterMeta').textContent=`${bgEditCanvas.width} × ${bgEditCanvas.height} • ${humanSize(b.size)} • refined PNG`},120)}
$('bgPreviewMode')?.addEventListener('change',applyBgPreviewMode);
async function verifyTransparentBlob(blob){
 if(!(blob instanceof Blob)||blob.size<120)throw Error('Output file is missing or empty.');
 const bm=await createImageBitmap(blob);try{const c=document.createElement('canvas');c.width=64;c.height=64;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(bm,0,0,64,64);const st=canvasAlphaStats(c);if(st.visible<.015||st.clear<.012)throw Error('PNG verification detected blank or opaque output. Download disabled.');}finally{bm.close?.();}
}
async function metadataSignals(fileOrBlob){const b=new Uint8Array(await fileOrBlob.arrayBuffer()),sig=[];if(b[0]===0xff&&b[1]===0xd8){let i=2;while(i+4<b.length&&b[i]===0xff){const m=b[i+1],len=(b[i+2]<<8)|b[i+3];if(m===0xe1)sig.push('EXIF/XMP (APP1)');if(m===0xed)sig.push('IPTC (APP13)');if(!len||m===0xda)break;i+=2+len}}else if(b[0]===0x89&&b[1]===0x50&&b[2]===0x4e&&b[3]===0x47){let i=8;while(i+12<=b.length){const len=(b[i]<<24)|(b[i+1]<<16)|(b[i+2]<<8)|b[i+3],t=String.fromCharCode(...b.slice(i+4,i+8));if(['eXIf','tEXt','zTXt','iTXt'].includes(t))sig.push(t);i+=12+Math.max(0,len);if(t==='IEND')break}}return[...new Set(sig)]}
async function downloadCurrent(){try{
 if(id==='print-size'){const w=Number($('printW').value),h=Number($('printH').value),dpi=Number($('printDpi').value);if(!w||!h||!dpi)throw Error('Enter valid values.');$('status').innerHTML=`<strong>${(w/dpi).toFixed(2)} × ${(h/dpi).toFixed(2)} inches</strong><br>${(w/dpi*2.54).toFixed(2)} × ${(h/dpi*2.54).toFixed(2)} cm at ${dpi} DPI`;return}
 if(id==='image-base64')return convertBase64();
 if(id==='base64-image')return decodeBase64();
 if(!currentImg)throw Error('Please select an image first.');if(id==='image-convert'&&/image\/(gif|webp)/i.test(currentFile?.type||'')&&!$('allowFirstFrame')?.checked)throw Error('GIF/WebP may be animated. DoKitly will not silently flatten animation. Check “extract only the first frame” to continue intentionally.');let type=selectedType(id==='image-bg-remove'),blob,c;
 if(id==='image-watermark'&&wmMode==='remove'){if(!wmMask)throw Error('Mark the watermark first or use Auto Detect.');setStatus('Reconstructing the masked area at full resolution…');c=wmBuildResult(true);type=selectedType(false);blob=await blobFromCanvas(c,type,quality());preparedResultBlob=blob;preparedResultType=type;preparedResultName='DoKitly_Watermark_Studio_Removed.'+extForType(type);showCanvasPreview(c,`${c.width} × ${c.height} • ${humanSize(blob.size)}`);showCompareSlider(c);if($('finalImageDownload'))$('finalImageDownload').disabled=false;setStatus('Full-resolution cleaned result prepared. Inspect details before downloading.','Processed:');return}
 if(id==='image-bg-remove'){preparedResultBlob=null;preparedResultName=null;if($('finalImageDownload'))$('finalImageDownload').disabled=true;setStatus('Removing background automatically…');const result=await autoRemoveBackground(currentImg);c=result.canvas;type='image/png';blob=await blobFromCanvas(c,type);await verifyTransparentBlob(blob);preparedResultBlob=blob;preparedResultType=type;preparedResultName=outName(id,type);bindBgEditor(c);if($('finalImageDownload'))$('finalImageDownload').disabled=false;setStatus(`${result.method} processed. Use Erase/Restore for edge cleanup, then download the full-resolution PNG.`,'Processed:');return}
 if(id==='image-passport'){c=drawVisual(true);const bg=$('passportBg')?.value||'keep';if(bg!=='keep'){setStatus('Detecting subject and replacing background…');c=await removePersonBackground(c,bg)}type=selectedType(false);const target=Number($('passportTargetKB')?.value||0);if(target>0&&type!=='image/png'){const limit=target*1024;let lo=.02,hi=.98,hit=null;for(let i=0;i<12;i++){const q=(lo+hi)/2,b=await blobFromCanvas(c,type,q);if(b.size<=limit){hit=b;lo=q}else hi=q}blob=hit||await blobFromCanvas(c,type,.02)}else blob=await blobFromCanvas(c,type,quality());preparedResultBlob=blob;preparedResultType=type;preparedResultName=outName(id,type);showCanvasPreview(c,`${c.width} × ${c.height} • ${humanSize(blob.size)}`);if($('finalImageDownload'))$('finalImageDownload').disabled=false;setStatus('Passport photo processed. Review framing/background, then download.','Processed:');return}
 if(id==='image-target'){const kb=$('targetSelect').value==='custom'?Number($('targetCustom').value):Number($('targetSelect').value);if(!kb)throw Error('Enter a target size.');if($('processBtn')){$('processBtn').disabled=true;$('processBtn').textContent='Compressing…'};const r=await compressToKB(kb,type,true);if($('processBtn')){$('processBtn').disabled=false;$('processBtn').textContent='Compress Image'};if(!r.blob)throw Error('Could not create a compressed result.');targetResultBlob=r.blob;targetResultType=type;if($('targetDownloadBtn'))$('targetDownloadBtn').disabled=false;showCanvasPreview(r.canvas,`${r.canvas.width} × ${r.canvas.height} • ${humanSize(r.blob.size)}`);setStatus(r.miss?`Closest result: ${humanSize(r.blob.size)}. Target ${kb} KB could not be reached without making the image extremely small.`:`Target: ${kb} KB • Result: ${humanSize(r.blob.size)}`,'Compressed:');return}
 c=drawVisual(true);if(!c)throw Error('Could not create a result.');if(id==='image-compress'&&Number($('targetKB')?.value)>0){const r=await compressToKB(Number($('targetKB').value),type,true);blob=r.blob;c=r.canvas}else blob=await blobFromCanvas(c,type,quality());if(id==='image-exif'){const remain=await metadataSignals(blob);if(remain.length)throw Error(`Metadata verification found remaining container(s): ${remain.join(', ')}. Download blocked.`)}preparedResultBlob=blob;preparedResultType=type;preparedResultName=outName(id,type);showCanvasPreview(c,`${c.width} × ${c.height} • ${humanSize(blob.size)}`);if($('finalImageDownload'))$('finalImageDownload').disabled=false;setStatus(`${humanSize(currentFile.size)} → ${humanSize(blob.size)}. Review preview, then download.`,'Processed:')
 }catch(e){if(id==='image-bg-remove'){preparedResultBlob=null;preparedResultName=null;if($('finalImageDownload'))$('finalImageDownload').disabled=true;}setStatus(e.message)}}

async function convertBase64(){if(!currentFile)throw Error('Please select an image first.');const bytes=new Uint8Array(await currentFile.arrayBuffer());let binary='';const CHUNK=0x8000;for(let i=0;i<bytes.length;i+=CHUNK)binary+=String.fromCharCode(...bytes.subarray(i,i+CHUNK));const b64=btoa(binary),mime=currentFile.type&&currentFile.type.startsWith('image/')?currentFile.type:'application/octet-stream',val=`data:${mime};base64,${b64}`;const decoded=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));if(decoded.length!==bytes.length)throw Error('Base64 verification failed: decoded size differs.');for(let i=0;i<bytes.length;i++){if(decoded[i]!==bytes[i])throw Error(`Base64 verification failed at byte ${i}.`)}$('base64Out').value=val;$('copyBtn').disabled=false;$('saveBase64Btn').disabled=false;$('openVerifiedBtn').disabled=false;$('base64Count').textContent=`• ${val.length.toLocaleString()} chars • ${decoded.length.toLocaleString()} bytes verified`;if(verifiedBlobURL)URL.revokeObjectURL(verifiedBlobURL);verifiedBlobURL=URL.createObjectURL(new Blob([decoded],{type:mime}));$('afterStage').innerHTML=`<img src="${verifiedBlobURL}" alt="Verified decoded image">`;$('afterMeta').textContent=`${decoded.length.toLocaleString()} bytes • exact match`;setStatus('Decoded bytes match the uploaded file exactly. Use “Open verified image” instead of pasting a huge Data URL into Chrome’s address bar.','Verified:')}
async function decodeBase64(){let val=$('base64In').value.trim().replace(/\s+/g,'');const m=val.match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/);if(!m)throw Error('Paste a complete data:image/...;base64,... URL.');let bin;try{bin=atob(m[2])}catch{throw Error('Invalid Base64 data.')}const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0)),blob=new Blob([bytes],{type:m[1]});if(verifiedBlobURL)URL.revokeObjectURL(verifiedBlobURL);verifiedBlobURL=URL.createObjectURL(blob);const im=new Image();im.onload=()=>{$('afterStage').innerHTML=`<img src="${verifiedBlobURL}" alt="Decoded image">`;$('afterMeta').textContent=`${im.width} × ${im.height} • ${humanSize(blob.size)}`;setStatus('Base64 decoded successfully.','Done:')};im.onerror=()=>setStatus('The Base64 decoded, but it is not a valid image.');im.src=verifiedBlobURL}
$('copyBtn')?.addEventListener('click',async()=>{const v=$('base64Out').value;if(!v)return;try{await navigator.clipboard.writeText(v);setStatus(`Copied all ${v.length.toLocaleString()} characters.`,'Copied:')}catch{$('base64Out').focus();$('base64Out').select();const ok=document.execCommand('copy');setStatus(ok?`Copied all ${v.length.toLocaleString()} characters.`:'Clipboard copy was blocked. Use Save .txt instead.')}});
$('saveBase64Btn')?.addEventListener('click',()=>{const v=$('base64Out').value;if(!v)return;const u=URL.createObjectURL(new Blob([v],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='DoKitly_Base64.txt';a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)});
$('openVerifiedBtn')?.addEventListener('click',()=>{if(verifiedBlobURL)window.open(verifiedBlobURL,'_blank','noopener')});
$('autoFaceBtn')?.addEventListener('click',async()=>{if(!currentImg){setStatus('Select an image first.');return}if(!('FaceDetector' in window)){setStatus('Automatic face detection is not supported in this browser. Use Zoom and Up/Down controls manually.');return}try{setStatus('Detecting face…');const fd=new FaceDetector({fastMode:true,maxDetectedFaces:1}),faces=await fd.detect(currentImg);if(!faces.length)throw Error('No clear face detected.');const b=faces[0].boundingBox,cx=b.x+b.width/2,cy=b.y+b.height/2;$('passportX').value=Math.round(Math.max(-100,Math.min(100,(.5-cx/currentImg.width)*115)));$('passportY').value=Math.round(Math.max(-100,Math.min(100,(.34-cy/currentImg.height)*125)));$('passportZoom').value=Math.round(Math.max(90,Math.min(180,135/(b.height/currentImg.height*3.2))));['passportX','passportY','passportZoom'].forEach(k=>$(k).dispatchEvent(new Event('input',{bubbles:true})));setStatus('Face centered. Fine-tune zoom/position if needed.','Auto:')}catch(e){setStatus(e.message||'Could not detect face.')}});
$('bgResetBtn')?.addEventListener('click',()=>{$('fileInput')?.click()});
$('processBtn')?.addEventListener('click',()=>{if(id==='multi-resize'||id==='multi-compress')processBatch();else downloadCurrent()});$('cancelBatchBtn')?.addEventListener('click',()=>{batchCancelled=true});$('retryBatchBtn')?.addEventListener('click',()=>processBatch(true));
$('targetDownloadBtn')?.addEventListener('click',()=>{if(!targetResultBlob||!targetResultType){setStatus('Compress the image first.');return}triggerDownload(targetResultBlob,outName('image-target',targetResultType));setStatus(`Downloaded ${humanSize(targetResultBlob.size)} image.`,'Downloaded:')});
$('finalImageDownload')?.addEventListener('click',()=>{const blob=batchZipBlob||preparedResultBlob;if(!blob){setStatus('Process the result first.');return}triggerDownload(blob,preparedResultName||outName(id,preparedResultType||selectedType(id==='image-bg-remove')));setStatus(`Downloaded ${preparedResultName||'processed file'}.`,'Downloaded:')});
if(id==='image-target'){['targetSelect','targetCustom','format'].forEach(k=>$(k)?.addEventListener('change',()=>{targetResultBlob=null;targetResultType=null;if($('targetDownloadBtn'))$('targetDownloadBtn').disabled=true}));}

function bindColorCanvas(img){const stage=$('beforeStage');if(!stage)return;const c=document.createElement('canvas'),max=260,sc=Math.min(1,max/Math.max(img.width,img.height));c.width=Math.round(img.width*sc);c.height=Math.round(img.height*sc);const x=c.getContext('2d');x.drawImage(img,0,0,c.width,c.height);stage.innerHTML='';stage.appendChild(c);c.style.cursor='crosshair';c.onclick=e=>{const r=c.getBoundingClientRect(),px=Math.floor((e.clientX-r.left)*c.width/r.width),py=Math.floor((e.clientY-r.top)*c.height/r.height),d=x.getImageData(px,py,1,1).data,hex='#'+[d[0],d[1],d[2]].map(v=>v.toString(16).padStart(2,'0')).join('').toUpperCase();$('swatch').style.background=hex;$('hexOut').textContent=hex;$('rgbOut').textContent=`RGB ${d[0]}, ${d[1]}, ${d[2]}`}}

const crcTable=(()=>{let t=[];for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();
function crc32(u8){let c=0xffffffff;for(const b of u8)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}function le16(n){return[n&255,(n>>>8)&255]}function le32(n){return[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]}
async function makeZip(files){const enc=new TextEncoder(),parts=[],central=[];let offset=0;for(const f of files){const name=enc.encode(f.name),data=new Uint8Array(await f.blob.arrayBuffer()),crc=crc32(data);const local=new Uint8Array([...le32(0x04034b50),...le16(20),...le16(0),...le16(0),...le16(0),...le16(0),...le32(crc),...le32(data.length),...le32(data.length),...le16(name.length),...le16(0),...name]);parts.push(local,data);const cent=new Uint8Array([...le32(0x02014b50),...le16(20),...le16(20),...le16(0),...le16(0),...le16(0),...le16(0),...le32(crc),...le32(data.length),...le32(data.length),...le16(name.length),...le16(0),...le16(0),...le16(0),...le16(0),...le32(0),...le32(offset),...name]);central.push(cent);offset+=local.length+data.length}const centralSize=central.reduce((n,a)=>n+a.length,0),end=new Uint8Array([...le32(0x06054b50),...le16(0),...le16(0),...le16(files.length),...le16(files.length),...le32(centralSize),...le32(offset),...le16(0)]);return new Blob([...parts,...central,end],{type:'application/zip'})}
async function passportSheet(){if(id!=='image-passport'||!currentImg)return;const photo=drawVisual(true);if(!photo)throw Error('Process a passport photo first.');const dpi=Number($('dpi')?.value)||300,W=Math.round(6*dpi),H=Math.round(4*dpi),sheet=document.createElement('canvas');sheet.width=W;sheet.height=H;const x=sheet.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,W,H);const gap=Math.round(.12*dpi),cols=Math.max(1,Math.floor((W+gap)/(photo.width+gap))),rows=Math.max(1,Math.floor((H+gap)/(photo.height+gap))),count=Math.min(cols*rows,12);for(let i=0;i<count;i++){const c=i%cols,r=Math.floor(i/cols);x.drawImage(photo,c*(photo.width+gap),r*(photo.height+gap))}const blob=await blobFromCanvas(sheet,'image/jpeg',.94),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='DoKitly_Passport_Photo_Print_Sheet.jpg';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);photo.width=photo.height=sheet.width=sheet.height=1}
$('passportSheetBtn')?.addEventListener('click',()=>passportSheet().catch(e=>setStatus(e.message)));
async function processBatch(retry=false){try{const files=retry?batchFailed:[...($('fileInput').files||[])];if(!files.length)throw Error('Select one or more images.');batchCancelled=false;batchFailed=[];$('batchList').innerHTML='';const done=[];for(let i=0;i<files.length;i++){if(batchCancelled){setStatus(`Cancelled after ${done.length} item(s).`);break}const file=files[i];let img,url;try{({img,url}=await readImage(file));}catch(err){batchFailed.push(file);$('batchList').insertAdjacentHTML('beforeend',`<div class="batch-row"><span>${esc(file.name)} • failed</span><span>!</span></div>`);continue}let type=typeFor(file,$('format').value,false),c;if(id==='multi-resize'){const mw=Number($('batchWidth').value)||1200;let w=img.width,h=img.height;if(w>mw){h*=mw/w;w=mw}c=canvasDraw(img,w,h,type)}else c=canvasDraw(img,img.width,img.height,type);const blob=await blobFromCanvas(c,type,id==='multi-compress'?quality():.92),name=outName(id,type,i+1);done.push({name,blob});$('batchList').insertAdjacentHTML('beforeend',`<div class="batch-row"><span>${esc(name)} • ${humanSize(blob.size)}</span><span>✓</span></div>`);URL.revokeObjectURL(url);c.width=c.height=1}if($('retryBatchBtn'))$('retryBatchBtn').disabled=!batchFailed.length;if(!done.length){if(batchCancelled)return;throw Error('No files were processed successfully.')}const zip=await makeZip(done);batchZipBlob=zip;preparedResultName=`DoKitly_${(TOOL[id]?.name||'Batch_Images').replace(/[^a-z0-9]+/gi,'_')}.zip`;if($('finalImageDownload'))$('finalImageDownload').disabled=false;setStatus(`${done.length} images packed into ${preparedResultName}. Review the list, then download.`,'Processed:')}catch(e){setStatus(e.message)}}


/* Build 6 final preview fit guard — keeps every processed image/canvas fully inside its fixed preview box. */
(()=>{
 const init=()=>{
  const stage=$('afterStage');if(!stage)return;
  const refit=()=>requestAnimationFrame(()=>fitPreviewMedia(stage));
  new MutationObserver(refit).observe(stage,{childList:true,subtree:true});
  if('ResizeObserver' in window)new ResizeObserver(refit).observe(stage);
  window.addEventListener('resize',refit,{passive:true});
  refit();
 };
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();

/* Build 7 global DoKitly color selector — replaces plain browser color bars visually. */
(()=>{
 const swatches=['#111827','#ffffff','#2563eb','#14b8a6','#ef4444','#f59e0b','#8b5cf6','#ec4899'];
 function enhance(input){if(!input||input.dataset.dmoColor==='1')return;input.dataset.dmoColor='1';const wrap=document.createElement('div');wrap.className='dmo-color-orb';const btn=document.createElement('button');btn.type='button';btn.className='dmo-color-orb-btn';btn.innerHTML=`<span class="dmo-color-dot"></span><b>Color</b><span>⌄</span>`;const pop=document.createElement('div');pop.className='dmo-color-pop';pop.hidden=true;swatches.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='dmo-color-chip';b.style.setProperty('--chip',c);b.title=c;b.onclick=()=>{input.value=c;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));pop.hidden=true;sync()};pop.appendChild(b)});const custom=document.createElement('label');custom.className='dmo-custom-color';custom.innerHTML='<span>＋</span>';input.parentNode.insertBefore(wrap,input);wrap.append(btn,pop);custom.appendChild(input);pop.appendChild(custom);function sync(){btn.querySelector('.dmo-color-dot').style.background=input.value;pop.querySelectorAll('.dmo-color-chip').forEach(x=>x.classList.toggle('active',x.title.toLowerCase()===input.value.toLowerCase()))}btn.onclick=()=>pop.hidden=!pop.hidden;input.addEventListener('input',sync);document.addEventListener('click',e=>{if(!wrap.contains(e.target))pop.hidden=true});sync()}
 function scan(){document.querySelectorAll('input[type="color"]').forEach(enhance)}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',scan,{once:true});else scan();new MutationObserver(scan).observe(document.body,{childList:true,subtree:true});
})();
