(() => {
const defs={
"pdf-editor":{"name":"PDF Editor","icon":"✏️","desc":"Edit text, pages, numbering, watermark and rotation with a live preview."},
"pdf-merge":{"name":"Merge PDF","icon":"🧩","desc":"Combine multiple PDF files and arrange them in the exact order you want."},
"pdf-split":{"name":"Split PDF","icon":"✂️","desc":"Split or extract selected PDF pages with page preview and flexible output options."},
"pdf-compress":{"name":"Compress PDF","icon":"🗜️","desc":"Choose the compression level and preview the document before download."},
"images-to-pdf":{"name":"Images to PDF","icon":"🖼️","desc":"Arrange uploaded images page-by-page and create one ordered PDF."},
"pdf-to-jpg":{"name":"PDF to JPG","icon":"📸","desc":"Convert one PDF page to JPG directly, or multiple pages into a ZIP."},
"pdf-to-png":{"name":"PDF to PNG","icon":"🌄","desc":"Convert PDF pages into PNG images."},
"pdf-to-word":{"name":"PDF to Word","icon":"W","desc":"Create an editable DOCX while preserving page structure and text layout as closely as browser conversion allows."},
"pdf-rotate":{"name":"Rotate PDF","icon":"🔄","desc":"Rotate all or selected PDF pages."},
"pdf-reorder":{"name":"Reorder PDF Pages","icon":"↕️","desc":"Rearrange PDF pages visually and save the chosen order."},
"pdf-delete-pages":{"name":"Delete PDF Pages","icon":"🗑️","desc":"Select unwanted pages visually and remove them."},
"pdf-extract-pages":{"name":"Extract PDF Pages","icon":"📤","desc":"Extract selected pages into one PDF or download each page separately in a ZIP."},
"pdf-duplicate-pages":{"name":"Duplicate PDF Pages","icon":"📑","desc":"Choose pages, number of copies and where duplicated pages should be inserted."},
"pdf-page-viewer":{"name":"PDF Page Viewer","icon":"👁️","desc":"Preview and inspect PDF pages. Page preview is also built into the editing tools."},
"pdf-page-numbers":{"name":"Add Page Numbers","icon":"🔢","desc":"Add page numbers with position, range, start number, size and margin controls."},
"pdf-add-text":{"name":"Add Text to PDF","icon":"T","desc":"Place editable text instructions on selected PDF pages with position, size and color controls."},
"pdf-watermark":{"name":"Watermark PDF","icon":"💧","desc":"Add a text watermark to selected PDF pages."},
"pdf-metadata":{"name":"PDF Metadata Viewer","icon":"🔎","desc":"View title, author, subject and PDF information."},
"pdf-edit-metadata":{"name":"Edit PDF Metadata","icon":"📝","desc":"Edit title, author, subject and keywords."},
"pdf-remove-metadata":{"name":"Remove PDF Metadata","icon":"🧹","desc":"Clear common metadata fields from a PDF."},
"pdf-paper-size":{"name":"PDF Paper Size Changer","icon":"📐","desc":"Place PDF pages onto common paper sizes."},
"pdf-margin":{"name":"PDF Margin Tool","icon":"↔️","desc":"Add clean margins around PDF pages."},
"pdf-crop":{"name":"PDF Crop Tool","icon":"✂","desc":"Adjust PDF page crop boxes."},
"text-to-pdf":{"name":"Text to PDF","icon":"📄","desc":"Create a PDF from plain text."},
"html-to-pdf":{"name":"HTML to PDF","icon":"</>","desc":"Create a PDF from HTML content."},
"pdf-info":{"name":"PDF Info / Analyzer","icon":"ℹ️","desc":"Check page count, dimensions and document details."},
"pdf-protect":{"name":"Password Protect PDF","icon":"🔐","desc":"Add a password to a PDF and download a genuinely protected copy."},
"pdf-unlock":{"name":"Unlock PDF","icon":"🔓","desc":"Open a PDF you are authorized to access where browser support allows."},
"pdf-grayscale":{"name":"PDF Grayscale","icon":"◐","desc":"Render PDF pages in grayscale and create a new PDF."},
"blank-pdf":{"name":"Blank PDF Generator","icon":"➕","desc":"Generate blank PDF pages in common sizes."}};
const id=document.body.dataset.tool,d=defs[id],root=document.getElementById('toolRoot');
if(!d||!root)return;
if(window.pdfjsLib)pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';
let files=[],primary=null,pageCount=0,selectedPages=new Set(),fileOrder=[],imageOrder=[],lastPdfJs=null,encryptedFallback=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const byId=x=>document.getElementById(x);
const download=async(bytes,name,type='application/pdf')=>{const blob=bytes instanceof Blob?bytes:new Blob([bytes],{type});if(window.DoKitlyDownload?.routeBlob){await window.DoKitlyDownload.routeBlob(blob,{filename:name,mimeType:type,tool:id});return}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1500)};
function title(){return `<div class="it-title"><span class="ico">${d.icon}</span><div><h1>${d.name}</h1><p>${d.desc}</p></div></div>`}
function fileInput(multiple=false,accept='application/pdf'){return `<div class="dropzone upload-row pdf-upload-row"><span class="upload-name" id="uploadName">${multiple?'Select files':'Select PDF'}</span><label class="file-pick-btn">Choose File<input id="pdfFile" type="file" ${multiple?'multiple':''} accept="${accept}" hidden></label><span class="pdf-upload-icon">${accept.includes('image')?'🖼️':'📄'}</span></div>`}
function field(label,html,wide=''){return `<div class="field ${wide}"><label>${label}</label>${html}</div>`}
function advanced(inner,open=false){return `<details class="advanced-box" ${open?'open':''}><summary>Advanced options</summary><div class="advanced-content">${inner}</div></details>`}
function actionLabel(){return ({'pdf-editor':'Apply & Download PDF','pdf-merge':'Merge PDFs','pdf-split':'Split PDF','pdf-compress':'Compress PDF','images-to-pdf':'Create PDF','pdf-to-jpg':'Convert to JPG','pdf-to-png':'Convert to PNG','pdf-to-word':'Convert to Editable Word','pdf-delete-pages':'Delete Selected Pages','pdf-extract-pages':'Extract Pages','pdf-duplicate-pages':'Duplicate Pages','pdf-page-numbers':'Add Page Numbers','pdf-add-text':'Add Text & Download','pdf-rotate':'Rotate PDF','pdf-reorder':'Save Page Order','pdf-page-viewer':'Load All Pages','pdf-watermark':'Add Watermark','pdf-paper-size':'Change Paper Size','pdf-margin':'Add Margins','pdf-crop':'Crop PDF','pdf-grayscale':'Convert to Grayscale','pdf-unlock':'Unlock & Download PDF','pdf-protect':'Password Protect PDF','pdf-info':'Analyze PDF','pdf-metadata':'Analyze PDF','pdf-edit-metadata':'Save Metadata','pdf-remove-metadata':'Remove Metadata','blank-pdf':'Create Blank PDF','text-to-pdf':'Create PDF','html-to-pdf':'Create PDF'})[id]||'Process PDF'}
function toolControls(){
 const multi=id==='pdf-merge'||id==='images-to-pdf'; const accept=id==='images-to-pdf'?'image/*':'application/pdf'; let c='';
 if(!['text-to-pdf','html-to-pdf','blank-pdf'].includes(id))c+=fileInput(multi,accept);
 if(id==='pdf-merge')c+=`<div class="helper-note">Upload 2 or more PDFs. Drag the cards below to set merge order.</div><div id="fileOrder" class="order-list"></div>`;
 if(id==='images-to-pdf')c+=`<div class="helper-note">Drag images into the exact page order. Page numbers update automatically.</div><div id="imageOrder" class="order-grid"></div>`;
 if(['pdf-split','pdf-extract-pages'].includes(id))c+=field('Pages / ranges','<input id="pages" placeholder="e.g. 1,3,5-8">')+field('Output mode',`<select id="extractMode"><option value="combined">Selected pages in one PDF</option><option value="separate">Each selected page separately (ZIP)</option></select>`)+`<div class="helper-note">You can also click page thumbnails to select pages.</div>`;
 if(id==='pdf-delete-pages')c+=field('Pages to delete','<input id="pages" placeholder="e.g. 2,4-6">')+`<div class="helper-note">Click page thumbnails to mark pages for deletion.</div>`;
 if(id==='pdf-reorder')c+=`<div class="helper-note">Drag the page thumbnails into the new order. No page-number typing required.</div>`;
 if(id==='pdf-duplicate-pages')c+=field('Pages to duplicate','<input id="pages" placeholder="e.g. 2,4-6">')+`<div class="pdf-control-row">${field('Copies','<input id="copies" type="number" min="1" max="20" value="1">')}${field('Insert copies','<select id="duplicateWhere"><option value="after">After each selected page</option><option value="before">Before each selected page</option><option value="end">At end of document</option></select>')}</div>`;
 if(id==='pdf-rotate')c+=field('Pages','<input id="pages" placeholder="Leave blank for all pages">')+field('Rotation','<select id="angle"><option value="90">90° clockwise</option><option value="180">180°</option><option value="270">270° clockwise</option></select>');
 if(id==='pdf-compress')c+=`<div class="compression-cards"><label><input type="radio" name="compression" value="less" checked><span><b>Less Compression</b><small>Best quality • keeps vector content where possible</small></span></label><label><input type="radio" name="compression" value="medium"><span><b>Medium Compression</b><small>Balanced file size and visual quality</small></span></label><label><input type="radio" name="compression" value="maximum"><span><b>Maximum Compression</b><small>Smallest size • Premium later</small></span><em>PRO LATER</em></label></div>`;
 if(['pdf-add-text','pdf-editor'].includes(id)){
   c+=field('Text','<input id="txt" value="DoKitly" placeholder="Type text to add">');
   c+=`<div class="pdf-control-row">${field('Pages','<input id="textPages" value="1" placeholder="1,3-5 or all">')}${field('Position','<select id="textPos"><option value="top-left">Top left</option><option value="top-center">Top center</option><option value="top-right">Top right</option><option value="center">Center</option><option value="bottom-left">Bottom left</option><option value="bottom-center">Bottom center</option><option value="bottom-right">Bottom right</option></select>')}</div>`;
   c+=advanced(`<div class="pdf-control-row">${field('Font','<select id="font"><option value="Helvetica">Helvetica</option><option value="TimesRoman">Times Roman</option><option value="Courier">Courier</option></select>')}${field('Font size','<input id="size" type="number" min="6" max="144" value="28">')}</div><div class="pdf-control-row">${field('Text color','<input id="textColor" type="color" value="#111827">')}${field('Margin','<input id="textMargin" type="number" min="0" value="36">')}</div>`);
 }
 if(id==='pdf-editor')c+=advanced(`${field('Watermark text','<input id="wm" placeholder="Optional watermark">')}<div class="pdf-control-row">${field('Rotate selected pages','<select id="editorAngle"><option value="0">No rotation</option><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select>')}${field('Rotation pages','<input id="editorRotatePages" placeholder="e.g. 2,4-6">')}</div>${field('Page numbers','<select id="editorNumbering"><option value="off">Off</option><option value="bottom-center">Bottom center</option><option value="bottom-right">Bottom right</option><option value="top-center">Top center</option></select>')}${field('Delete pages','<input id="editorDeletePages" placeholder="Optional: 2,4-6">')}`,true);
 if(id==='pdf-page-numbers')c+=`<div class="pdf-control-row">${field('Position','<select id="pos"><option value="bottom-center">Bottom center</option><option value="bottom-left">Bottom left</option><option value="bottom-right">Bottom right</option><option value="top-center">Top center</option><option value="top-left">Top left</option><option value="top-right">Top right</option></select>')}${field('Pages','<input id="numberPages" value="all" placeholder="all or 2-8">')}</div>`+advanced(`<div class="pdf-control-row">${field('Start number','<input id="startNumber" type="number" value="1">')}${field('Font size','<input id="numberSize" type="number" min="6" max="72" value="11">')}</div>${field('Margin','<input id="numberMargin" type="number" min="0" value="20">')}`);
 if(id==='pdf-watermark')c+=field('Watermark text','<input id="wm" value="DoKitly">')+`<div class="pdf-control-row">${field('Pages','<input id="wmPages" value="all">')}${field('Opacity','<input id="wmOpacity" type="range" min="5" max="80" value="18">')}</div>`;
 if(id==='pdf-paper-size')c+=`<div class="pdf-control-row">${field('Target paper size','<select id="paperTarget"><option value="a4">A4</option><option value="letter">Letter</option><option value="legal">Legal</option><option value="a3">A3</option><option value="a5">A5</option></select>')}${field('Orientation','<select id="paperOrientation"><option value="auto">Auto</option><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select>')}</div>`+advanced(`${field('Fit mode','<select id="paperFit"><option value="fit">Fit entire page</option><option value="fill">Fill page (may crop)</option></select>')}${field('Page background','<select id="paperBg"><option value="white">White</option></select>')}`);
 if(id==='pdf-margin')c+=`<div class="pdf-control-row">${field('Margin size (pt)','<input id="marginSize" type="number" min="0" max="200" value="36">')}${field('Apply to','<select id="marginPagesMode"><option value="all">All pages</option><option value="custom">Selected pages</option></select>')}</div>`+field('Selected pages','<input id="marginPages" placeholder="e.g. 1,3-5">');
 if(id==='pdf-crop')c+=`<div class="pdf-control-row">${field('Left crop (pt)','<input id="cropLeft" type="number" min="0" value="0">')}${field('Right crop (pt)','<input id="cropRight" type="number" min="0" value="0">')}</div><div class="pdf-control-row">${field('Top crop (pt)','<input id="cropTop" type="number" min="0" value="0">')}${field('Bottom crop (pt)','<input id="cropBottom" type="number" min="0" value="0">')}</div>`+field('Pages','<input id="cropPages" value="all" placeholder="all or 1,3-5">');
 if(id==='pdf-grayscale')c+=`<div class="pdf-control-row">${field('Quality','<select id="grayQuality"><option value="1.5">Standard</option><option value="2">High</option><option value="1">Smaller file</option></select>')}${field('JPEG quality','<input id="grayJpeg" type="range" min="45" max="95" value="82">')}</div><div class="helper-note">Grayscale is rendered page-by-page for reliable output.</div>`;
 if(id==='pdf-unlock')c+=field('PDF password','<input id="pdfPassword" type="password" autocomplete="off" placeholder="Enter the PDF password">')+`<div class="helper-note">Creates a new unlocked copy by rendering each page. Use only on PDFs you are authorized to access.</div>`;
 if(id==='pdf-protect')c+=field('Open password','<input id="protectPassword" type="password" autocomplete="new-password" placeholder="Enter a password">')+field('Confirm password','<input id="protectPassword2" type="password" autocomplete="new-password" placeholder="Re-enter the password">')+`<div class="helper-note">Creates a new password-protected copy locally in your browser. To guarantee encryption with the current browser libraries, pages are rendered into the protected PDF.</div>`;
 if(id==='pdf-edit-metadata')c+=field('Title','<input id="title">')+field('Author','<input id="author">')+field('Subject','<input id="subject">')+field('Keywords','<input id="keywords" placeholder="comma, separated, keywords">');
 if(id==='text-to-pdf'||id==='html-to-pdf')c=field(id==='text-to-pdf'?'Text':'HTML',`<textarea class="pdf-textarea" id="source" placeholder="Enter content here..."></textarea>`,'wide');
 if(id==='blank-pdf')c=`<div class="pdf-control-row">${field('Page size','<select id="paper"><option value="a4">A4</option><option value="letter">Letter</option><option value="legal">Legal</option></select>')}${field('Pages','<input id="blankPages" type="number" min="1" max="100" value="1">')}</div>`;
 c+=`<div id="pagePicker" class="page-picker"></div><div class="pdf-actions"><button class="primary pdf-main-action" id="runBtn"><span>${actionLabel()}</span><b>→</b></button></div><div class="output pdf-result" id="result">${['text-to-pdf','html-to-pdf','blank-pdf'].includes(id)?'Ready.':'Choose a file to begin.'}</div>`;
 return c;
}
root.innerHTML=title()+`<section class="it-panel"><div class="editor-layout"><div class="editor-controls">${toolControls()}</div><aside class="editor-preview"><div class="live-preview-card"><div class="preview-head"><div><b>Live Processed Preview</b><small>Preview updates as you change options</small></div><span id="previewMeta">PDF</span></div><div class="preview-stage editor-after-stage" id="afterStage"><span class="preview-placeholder">Preview will appear here</span></div><div class="preview-footer" id="previewFooter">Download only after you are happy with the preview.</div></div></aside></div></section>`;
function setResult(msg,bad=false){const r=byId('result');if(!r)return;r.textContent=msg;r.classList.toggle('is-error',bad)}
function parsePages(s,max,allOnBlank=true){s=String(s??'').trim().toLowerCase();if((!s&&allOnBlank)||s==='all')return [...Array(max)].map((_,i)=>i);if(!s)return[];const out=[];for(const part0 of s.split(',')){const p=part0.trim();if(!p)continue;if(p.includes('-')){let[a,b]=p.split('-').map(Number);if(!Number.isFinite(a)||!Number.isFinite(b))continue;if(a>b)[a,b]=[b,a];for(let n=a;n<=b;n++)if(n>=1&&n<=max)out.push(n-1)}else{const n=Number(p);if(n>=1&&n<=max)out.push(n-1)}}return [...new Set(out)]}
async function loadLib(file=primary){if(!file)throw Error('Choose a PDF first.');const bytes=await file.arrayBuffer();try{return await PDFLib.PDFDocument.load(bytes)}catch(e){if(/encrypt/i.test(String(e?.message||e))){try{encryptedFallback=true;setResult('This PDF is encrypted. Trying compatible processing mode…');return await PDFLib.PDFDocument.load(bytes,{ignoreEncryption:true})}catch(_){throw Error('This PDF is password-protected or encrypted and cannot be edited in the browser. Please unlock it with the correct password first.')}}throw e}}
async function loadPdfJs(file=primary){if(!file)throw Error('Choose a PDF first.');const data=await file.arrayBuffer();try{return await pdfjsLib.getDocument({data}).promise}catch(e){if(e?.name==='PasswordException'||/password/i.test(String(e?.message||'')))throw Error('This PDF needs a password before it can be previewed. Please use an unlocked copy.');throw e}}
async function loadPdfJsWithPassword(file=primary,password=''){if(!file)throw Error('Choose a PDF first.');const data=await file.arrayBuffer();const task=pdfjsLib.getDocument({data,password:password||undefined});return await task.promise}
async function renderPageToCanvas(pdf,pageNo,scale=1){const p=await pdf.getPage(pageNo),vp=p.getViewport({scale}),c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);await p.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;return c}
async function showFirstPreview(file=primary){if(!file)return;const stage=byId('afterStage');try{const pdf=await loadPdfJs(file);lastPdfJs=pdf;pageCount=pdf.numPages;byId('previewMeta').textContent=`${pageCount} page${pageCount===1?'':'s'}`;const p=await pdf.getPage(1),vp=p.getViewport({scale:1});const maxW=Math.max(180,stage.clientWidth-24),maxH=Math.max(200,stage.clientHeight-24),scale=Math.min(maxW/vp.width,maxH/vp.height,1.35);const c=await renderPageToCanvas(pdf,1,scale);stage.innerHTML='';stage.appendChild(c);if(needsPagePicker())await buildPagePicker(pdf)}catch(e){stage.innerHTML=`<span class="preview-placeholder">${esc(e.message||'Preview unavailable')}</span>`;setResult(e.message||'Preview unavailable',true)}}
function needsPagePicker(){return ['pdf-split','pdf-extract-pages','pdf-delete-pages','pdf-duplicate-pages','pdf-rotate','pdf-reorder','pdf-page-viewer','pdf-editor','pdf-margin','pdf-crop'].includes(id)}
async function buildPagePicker(pdf){const box=byId('pagePicker');if(!box)return;box.innerHTML='<div class="section-mini-title">Page preview</div><div class="pdf-pages selectable-pages" id="pageCards"></div>';const cards=byId('pageCards');const max=Math.min(pdf.numPages,80);for(let i=1;i<=max;i++){const c=await renderPageToCanvas(pdf,i,.18);const wrap=document.createElement('button');wrap.type='button';wrap.className='pdf-page page-card';wrap.dataset.page=String(i-1);wrap.draggable=id==='pdf-reorder';wrap.innerHTML=`<span class="thumb-slot"></span><small>Page ${i}</small>`;wrap.querySelector('.thumb-slot').appendChild(c);cards.appendChild(wrap)}if(id==='pdf-reorder')enablePageReorder(cards);else cards.addEventListener('click',e=>{const btn=e.target.closest('.page-card');if(!btn)return;const n=Number(btn.dataset.page);if(selectedPages.has(n))selectedPages.delete(n);else selectedPages.add(n);btn.classList.toggle('selected',selectedPages.has(n));syncSelectionField();updateLivePreviewDebounced()})}
function syncSelectionField(){const arr=[...selectedPages].sort((a,b)=>a-b).map(x=>x+1);const el=byId('pages');if(el&&id!=='pdf-reorder')el.value=arr.join(',')}
function enablePageReorder(container){let drag=null;container.querySelectorAll('.page-card').forEach(card=>{card.addEventListener('dragstart',()=>{drag=card;card.classList.add('dragging')});card.addEventListener('dragend',()=>{card.classList.remove('dragging');drag=null;renumberPageCards(container);updateLivePreviewDebounced()});card.addEventListener('dragover',e=>{e.preventDefault();const target=e.currentTarget;if(!drag||drag===target)return;const r=target.getBoundingClientRect();container.insertBefore(drag,e.clientX<r.left+r.width/2?target:target.nextSibling)})})}
function renumberPageCards(container){[...container.querySelectorAll('.page-card')].forEach((c,i)=>c.querySelector('small').textContent=`Position ${i+1} • Page ${Number(c.dataset.page)+1}`)}
function getReorderIndices(){return [...document.querySelectorAll('#pageCards .page-card')].map(x=>Number(x.dataset.page))}
function makeOrderCard(file,index,type='pdf'){const div=document.createElement('div');div.className='order-item';div.draggable=true;div.dataset.index=String(index);div.innerHTML=`<span class="drag-handle">⋮⋮</span><span class="order-thumb">${type==='image'?'<img alt="">':'📄'}</span><span class="order-info"><b>${esc(file.name)}</b><small>${type==='image'?`PDF page ${index+1}`:'Drag to reorder'}</small></span><button type="button" class="remove-order" aria-label="Remove">×</button>`;if(type==='image'){const img=div.querySelector('img');img.src=URL.createObjectURL(file);img.onload=()=>URL.revokeObjectURL(img.src)}return div}
function renderFileOrder(){const box=byId('fileOrder');if(!box)return;box.innerHTML='';fileOrder.forEach((f,i)=>box.appendChild(makeOrderCard(f,i,'pdf')));enableOrderList(box,'pdf')}
function renderImageOrder(){const box=byId('imageOrder');if(!box)return;box.innerHTML='';imageOrder.forEach((f,i)=>box.appendChild(makeOrderCard(f,i,'image')));enableOrderList(box,'image')}
function enableOrderList(box,type){let dragIndex=null;box.querySelectorAll('.order-item').forEach((item,i)=>{item.addEventListener('dragstart',()=>{dragIndex=i;item.classList.add('dragging')});item.addEventListener('dragend',()=>{item.classList.remove('dragging');dragIndex=null});item.addEventListener('dragover',e=>e.preventDefault());item.addEventListener('drop',e=>{e.preventDefault();if(dragIndex===null||dragIndex===i)return;const arr=type==='image'?imageOrder:fileOrder;const [m]=arr.splice(dragIndex,1);arr.splice(i,0,m);type==='image'?renderImageOrder():renderFileOrder();updateLivePreviewDebounced()});item.querySelector('.remove-order').addEventListener('click',()=>{const arr=type==='image'?imageOrder:fileOrder;arr.splice(i,1);files=[...arr];primary=files[0]||null;type==='image'?renderImageOrder():renderFileOrder();byId('uploadName').textContent=files.length?`${files.length} file${files.length===1?'':'s'} selected`:'Select files';updateLivePreviewDebounced()})})}
const input=byId('pdfFile');if(input)input.addEventListener('change',async()=>{files=[...input.files];primary=files[0]||null;selectedPages.clear();byId('uploadName').textContent=files.length>1?`${files.length} files selected`:(primary?primary.name:(id==='images-to-pdf'?'Select images':'Select PDF'));if(id==='pdf-merge'){fileOrder=[...files];renderFileOrder()}if(id==='images-to-pdf'){imageOrder=[...files];renderImageOrder();await previewImages()}else if(primary&&/pdf/i.test(primary.type||primary.name))await showFirstPreview(primary);setResult(primary?`${files.length||1} file${files.length===1?'':'s'} ready.`:'Choose a file to begin.')});
async function previewImages(){const stage=byId('afterStage');if(!imageOrder.length){stage.innerHTML='<span class="preview-placeholder">Preview will appear here</span>';return}const img=document.createElement('img');img.src=URL.createObjectURL(imageOrder[0]);img.onload=()=>{URL.revokeObjectURL(img.src);byId('previewMeta').textContent=`${imageOrder.length} page${imageOrder.length===1?'':'s'}`};stage.innerHTML='';stage.appendChild(img)}
function hexRgb(hex){const n=parseInt(String(hex).replace('#',''),16);return PDFLib.rgb(((n>>16)&255)/255,((n>>8)&255)/255,(n&255)/255)}
function coords(p,text,font,size,pos,margin){const {width,height}=p.getSize(),tw=font.widthOfTextAtSize(text,size),th=size;let x=margin,y=height-margin-th;if(pos.includes('center'))x=(width-tw)/2;if(pos.endsWith('right'))x=width-margin-tw;if(pos.startsWith('bottom'))y=margin;if(pos==='center')y=(height-th)/2;return{x:Math.max(0,x),y:Math.max(0,y)}}
async function createProcessedBytes(forPreview=false){
 if(!primary)throw Error('Choose a PDF first.'); const pdf=await loadLib(),n=pdf.getPageCount();
 if(id==='pdf-delete-pages'){const del=new Set(selectedPages.size?[...selectedPages]:parsePages(byId('pages').value,n,false));if(!del.size)throw Error('Select at least one page to delete.');if(del.size>=n)throw Error('At least one page must remain.');for(let i=n-1;i>=0;i--)if(del.has(i))pdf.removePage(i);return pdf.save()}
 if(id==='pdf-reorder'){const order=getReorderIndices();if(!order.length)throw Error('Load the PDF first.');const out=await PDFLib.PDFDocument.create(),pgs=await out.copyPages(pdf,order);pgs.forEach(p=>out.addPage(p));return out.save()}
 if(id==='pdf-rotate'){const sel=selectedPages.size?[...selectedPages]:parsePages(byId('pages').value,n,true),ang=Number(byId('angle').value);sel.forEach(i=>{const p=pdf.getPage(i);p.setRotation(PDFLib.degrees((p.getRotation().angle+ang)%360))});return pdf.save()}
 if(id==='pdf-page-numbers'){const font=await pdf.embedFont(PDFLib.StandardFonts.Helvetica),sel=parsePages(byId('numberPages').value,n,true),start=Number(byId('startNumber').value)||1,size=Number(byId('numberSize').value)||11,margin=Number(byId('numberMargin').value)||20,pos=byId('pos').value;sel.forEach((pi,k)=>{const p=pdf.getPage(pi),text=String(start+k),xy=coords(p,text,font,size,pos,margin);p.drawText(text,{...xy,size,font,color:PDFLib.rgb(.12,.16,.22)})});return pdf.save()}
 if(id==='pdf-add-text'||id==='pdf-editor'){const txt=byId('txt').value,size=Number(byId('size').value)||28,margin=Number(byId('textMargin').value)||36,pos=byId('textPos').value,pages=parsePages(byId('textPages').value,n,true),fontKey=byId('font').value,font=await pdf.embedFont(PDFLib.StandardFonts[fontKey]||PDFLib.StandardFonts.Helvetica),color=hexRgb(byId('textColor').value);if(txt)pages.forEach(i=>{const p=pdf.getPage(i),xy=coords(p,txt,font,size,pos,margin);p.drawText(txt,{...xy,size,font,color})});if(id==='pdf-editor'){const wm=byId('wm').value;if(wm){const wf=font;pdf.getPages().forEach(p=>p.drawText(wm,{x:45,y:p.getHeight()/2,size:36,font:wf,opacity:.16,rotate:PDFLib.degrees(35)}))}const ang=Number(byId('editorAngle').value||0);if(ang){parsePages(byId('editorRotatePages').value,n,false).forEach(i=>{const p=pdf.getPage(i);p.setRotation(PDFLib.degrees((p.getRotation().angle+ang)%360))})}const num=byId('editorNumbering').value;if(num!=='off'){const nf=await pdf.embedFont(PDFLib.StandardFonts.Helvetica);pdf.getPages().forEach((p,i)=>{const text=String(i+1),xy=coords(p,text,nf,10,num,18);p.drawText(text,{...xy,size:10,font:nf})})}const del=parsePages(byId('editorDeletePages')?.value||'',pdf.getPageCount(),false);if(del.length>=pdf.getPageCount())throw Error('At least one page must remain.');for(const i of del.sort((a,b)=>b-a))pdf.removePage(i)}return pdf.save()}
 if(id==='pdf-watermark'){const txt=byId('wm').value||'DoKitly',font=await pdf.embedFont(PDFLib.StandardFonts.Helvetica),sel=parsePages(byId('wmPages').value,n,true),opacity=Math.max(.05,Math.min(.8,Number(byId('wmOpacity').value||18)/100));sel.forEach(i=>{const p=pdf.getPage(i);p.drawText(txt,{x:45,y:p.getHeight()/2,size:36,font,opacity,rotate:PDFLib.degrees(35)})});return pdf.save()}
 if(id==='pdf-paper-size'){const sizes={a4:[595.28,841.89],letter:[612,792],legal:[612,1008],a3:[841.89,1190.55],a5:[419.53,595.28]},base=sizes[byId('paperTarget').value]||sizes.a4,ori=byId('paperOrientation').value,fit=byId('paperFit').value,out=await PDFLib.PDFDocument.create();for(let i=0;i<n;i++){const src=pdf.getPage(i),sw=src.getWidth(),sh=src.getHeight();let [tw,th]=base;if(ori==='landscape'||(ori==='auto'&&sw>sh))[tw,th]=[Math.max(...base),Math.min(...base)];else [tw,th]=[Math.min(...base),Math.max(...base)];const ep=await out.embedPage(src);const scale=fit==='fill'?Math.max(tw/sw,th/sh):Math.min(tw/sw,th/sh),dw=sw*scale,dh=sh*scale,p=out.addPage([tw,th]);p.drawPage(ep,{x:(tw-dw)/2,y:(th-dh)/2,width:dw,height:dh})}return out.save()}
 if(id==='pdf-margin'){const m=Math.max(0,Math.min(200,Number(byId('marginSize').value)||0)),selMode=byId('marginPagesMode').value,sel=new Set(selMode==='all'?[...Array(n)].map((_,i)=>i):parsePages(byId('marginPages').value,n,false)),out=await PDFLib.PDFDocument.create();for(let i=0;i<n;i++){const src=pdf.getPage(i),ep=await out.embedPage(src),apply=sel.has(i),nw=src.getWidth()+(apply?m*2:0),nh=src.getHeight()+(apply?m*2:0),p=out.addPage([nw,nh]);p.drawPage(ep,{x:apply?m:0,y:apply?m:0,width:src.getWidth(),height:src.getHeight()})}return out.save()}
 if(id==='pdf-crop'){const l=Math.max(0,Number(byId('cropLeft').value)||0),r=Math.max(0,Number(byId('cropRight').value)||0),t=Math.max(0,Number(byId('cropTop').value)||0),b=Math.max(0,Number(byId('cropBottom').value)||0),sel=parsePages(byId('cropPages').value,n,true);for(const i of sel){const p=pdf.getPage(i),w=p.getWidth(),h=p.getHeight(),cw=w-l-r,ch=h-t-b;if(cw<20||ch<20)throw Error('Crop values are too large for one or more pages.');p.setCropBox(l,b,cw,ch)}return pdf.save()}
 return pdf.save({useObjectStreams:true,addDefaultPage:false})
}
async function previewBytes(bytes){const stage=byId('afterStage');const pdf=await pdfjsLib.getDocument({data:bytes.slice?bytes.slice(0):bytes}).promise;byId('previewMeta').textContent=`${pdf.numPages} page${pdf.numPages===1?'':'s'}`;const p=await pdf.getPage(1),vp=p.getViewport({scale:1}),scale=Math.min((stage.clientWidth-24)/vp.width,(stage.clientHeight-24)/vp.height,1.25);const c=await renderPageToCanvas(pdf,1,Math.max(.25,scale));stage.innerHTML='';stage.appendChild(c)}
let previewTimer=null;function updateLivePreviewDebounced(){clearTimeout(previewTimer);previewTimer=setTimeout(updateLivePreview,260)}
async function updateLivePreview(){if(!primary)return;try{if(['pdf-add-text','pdf-editor','pdf-page-numbers','pdf-watermark','pdf-delete-pages','pdf-rotate','pdf-reorder','pdf-paper-size','pdf-margin','pdf-crop'].includes(id)){const bytes=await createProcessedBytes(true);await previewBytes(bytes)}else if(id==='images-to-pdf')await previewImages();else if(id==='pdf-merge'&&fileOrder[0])await showFirstPreview(fileOrder[0]);}catch(e){/* do not interrupt typing with preview errors */}}
document.querySelectorAll('input,select,textarea').forEach(el=>{if(el.id!=='pdfFile')el.addEventListener('input',updateLivePreviewDebounced)});
async function createZip(entries,name){if(!window.JSZip)throw Error('ZIP library did not load. Please refresh and try again.');const zip=new JSZip();entries.forEach(e=>zip.file(e.name,e.data));download(await zip.generateAsync({type:'blob'}),name,'application/zip')}
async function run(){const btn=byId('runBtn');if(btn)btn.disabled=true;setResult('Processing…');try{
 if(id==='pdf-merge'){if(fileOrder.length<2)throw Error('Choose at least two PDF files.');const out=await PDFLib.PDFDocument.create();for(const f of fileOrder){const src=await loadLib(f),pgs=await out.copyPages(src,src.getPageIndices());pgs.forEach(p=>out.addPage(p))}download(await out.save(),'merged.pdf');setResult(`Merged ${fileOrder.length} PDFs in your chosen order.`);return}
 if(id==='images-to-pdf'){if(!imageOrder.length)throw Error('Choose one or more images.');const out=await PDFLib.PDFDocument.create();for(const f of imageOrder){const b=await f.arrayBuffer();let img;if(/png/i.test(f.type))img=await out.embedPng(b);else if(/jpe?g/i.test(f.type))img=await out.embedJpg(b);else{const bitmap=await createImageBitmap(f),c=document.createElement('canvas');c.width=bitmap.width;c.height=bitmap.height;c.getContext('2d').drawImage(bitmap,0,0);const blob=await new Promise(res=>c.toBlob(res,'image/jpeg',.92));img=await out.embedJpg(await blob.arrayBuffer())}const p=out.addPage([img.width,img.height]);p.drawImage(img,{x:0,y:0,width:img.width,height:img.height})}download(await out.save(),'images-to-pdf.pdf');setResult(`Created ${imageOrder.length}-page PDF in your chosen image order.`);return}
 if(id==='text-to-pdf'||id==='html-to-pdf'){const {jsPDF}=window.jspdf,doc=new jsPDF(),div=document.createElement('div');let s=byId('source').value;if(id==='html-to-pdf'){div.innerHTML=s;s=div.innerText}const lines=doc.splitTextToSize(s||' ',180);doc.text(lines,15,20);doc.save(id==='text-to-pdf'?'text.pdf':'html.pdf');setResult('PDF created.');return}
 if(id==='blank-pdf'){const map={a4:[595.28,841.89],letter:[612,792],legal:[612,1008]},out=await PDFLib.PDFDocument.create(),size=map[byId('paper').value],n=Math.max(1,Number(byId('blankPages').value)||1);for(let i=0;i<n;i++)out.addPage(size);download(await out.save(),'blank.pdf');setResult(`Created ${n} blank page(s).`);return}
 if(!primary)throw Error('Choose a PDF first.');
 if(id==='pdf-page-viewer'){const pdf=await loadPdfJs();await buildPagePicker(pdf);setResult(`Loaded ${pdf.numPages} page(s).`);return}
 if(id==='pdf-to-jpg'||id==='pdf-to-png'){const pdf=await loadPdfJs(),ext=id==='pdf-to-jpg'?'jpg':'png',type=id==='pdf-to-jpg'?'image/jpeg':'image/png',entries=[];for(let i=1;i<=pdf.numPages;i++){const c=await renderPageToCanvas(pdf,i,1.7),blob=await new Promise(res=>c.toBlob(res,type,.9));if(pdf.numPages===1)download(blob,`page-1.${ext}`,type);else entries.push({name:`page-${i}.${ext}`,data:blob})}if(pdf.numPages>1)await createZip(entries,`pdf-to-${ext}.zip`);setResult(pdf.numPages===1?`1-page PDF converted to ${ext.toUpperCase()} and downloaded directly.`:`${pdf.numPages} pages converted and packed into one ZIP.`);return}
 if(id==='pdf-to-word'){if(!window.docx)throw Error('Word conversion library did not load.');const pdf=await loadPdfJs(),sections=[];for(let i=1;i<=pdf.numPages;i++){const p=await pdf.getPage(i),vp=p.getViewport({scale:1}),tc=await p.getTextContent();const items=tc.items.filter(x=>x.str&&x.str.trim()).sort((a,b)=>{const ay=a.transform?.[5]||0,by=b.transform?.[5]||0;if(Math.abs(by-ay)>4)return by-ay;return (a.transform?.[4]||0)-(b.transform?.[4]||0)});const lines=[];let current=[],lastY=null;for(const x of items){const y=x.transform?.[5]||0;if(lastY===null||Math.abs(y-lastY)<5){current.push(x.str)}else{lines.push(current.join(' '));current=[x.str]}lastY=y}if(current.length)lines.push(current.join(' '));const children=lines.map(t=>new docx.Paragraph({children:[new docx.TextRun({text:t,size:22})],spacing:{after:70}}));sections.push({properties:{page:{size:{width:Math.round(vp.width*20*0.75),height:Math.round(vp.height*20*0.75)},margin:{top:500,right:500,bottom:500,left:500}}},children})}const doc=new docx.Document({sections}),blob=await docx.Packer.toBlob(doc);download(blob,'converted-editable.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document');setResult('Editable DOCX created with page-by-page structure and improved line layout. Complex tables/fonts may still need adjustment.');return}
 if(id==='pdf-compress'){const level=document.querySelector('input[name="compression"]:checked')?.value||'less';if(level==='less'){const pdf=await loadLib(),bytes=await pdf.save({useObjectStreams:true,addDefaultPage:false});download(bytes,'compressed-less.pdf');setResult(`Less compression complete: ${(primary.size/1024).toFixed(1)} KB → ${(bytes.length/1024).toFixed(1)} KB.`);return}const src=await loadPdfJs(),out=await PDFLib.PDFDocument.create(),cfg=level==='maximum'?{scale:.95,q:.52}:{scale:1.25,q:.72};for(let i=1;i<=src.numPages;i++){const c=await renderPageToCanvas(src,i,cfg.scale),blob=await new Promise(res=>c.toBlob(res,'image/jpeg',cfg.q)),img=await out.embedJpg(await blob.arrayBuffer()),orig=await src.getPage(i),vp=orig.getViewport({scale:1}),p=out.addPage([vp.width,vp.height]);p.drawImage(img,{x:0,y:0,width:vp.width,height:vp.height})}const bytes=await out.save({useObjectStreams:true});download(bytes,`compressed-${level}.pdf`);setResult(`${level[0].toUpperCase()+level.slice(1)} compression complete: ${(primary.size/1024).toFixed(1)} KB → ${(bytes.length/1024).toFixed(1)} KB. Raster compression can reduce text/vector editability.`);return}
 if(['pdf-split','pdf-extract-pages'].includes(id)){const pdf=await loadLib(),n=pdf.getPageCount(),sel=selectedPages.size?[...selectedPages].sort((a,b)=>a-b):parsePages(byId('pages').value,n,false);if(!sel.length)throw Error('Select or enter at least one valid page.');if(byId('extractMode').value==='separate'){const entries=[];for(const pi of sel){const out=await PDFLib.PDFDocument.create(),[p]=await out.copyPages(pdf,[pi]);out.addPage(p);entries.push({name:`page-${pi+1}.pdf`,data:await out.save()})}await createZip(entries,'extracted-pages.zip');setResult(`${sel.length} page(s) downloaded separately in a ZIP.`)}else{const out=await PDFLib.PDFDocument.create(),pgs=await out.copyPages(pdf,sel);pgs.forEach(p=>out.addPage(p));download(await out.save(),id==='pdf-split'?'split-selected-pages.pdf':'extracted-pages.pdf');setResult(`${sel.length} selected page(s) saved in one PDF.`)}return}
 if(id==='pdf-duplicate-pages'){const pdf=await loadLib(),n=pdf.getPageCount(),sel=new Set(selectedPages.size?[...selectedPages]:parsePages(byId('pages').value,n,false)),copies=Math.max(1,Math.min(20,Number(byId('copies').value)||1)),where=byId('duplicateWhere').value;if(!sel.size)throw Error('Select at least one page to duplicate.');const out=await PDFLib.PDFDocument.create(),append=[];for(let i=0;i<n;i++){if(where==='before'&&sel.has(i))for(let c=0;c<copies;c++){const[p]=await out.copyPages(pdf,[i]);out.addPage(p)}const[p]=await out.copyPages(pdf,[i]);out.addPage(p);if(where==='after'&&sel.has(i))for(let c=0;c<copies;c++){const[p2]=await out.copyPages(pdf,[i]);out.addPage(p2)}if(where==='end'&&sel.has(i))for(let c=0;c<copies;c++)append.push(i)}for(const i of append){const[p]=await out.copyPages(pdf,[i]);out.addPage(p)}download(await out.save(),'duplicated-pages.pdf');setResult('Selected pages duplicated with your chosen copy count and placement.');return}
 if(id==='pdf-info'||id==='pdf-metadata'){const pdf=await loadLib(),n=pdf.getPageCount(),p=pdf.getPage(0),sz=p.getSize();byId('result').innerHTML=`<strong>${n} page(s)</strong><small>First page: ${Math.round(sz.width)} × ${Math.round(sz.height)} pt<br>Title: ${esc(pdf.getTitle()||'—')}<br>Author: ${esc(pdf.getAuthor()||'—')}<br>Subject: ${esc(pdf.getSubject()||'—')}</small>`;return}
 if(id==='pdf-edit-metadata'){const pdf=await loadLib();pdf.setTitle(byId('title').value);pdf.setAuthor(byId('author').value);pdf.setSubject(byId('subject').value);pdf.setKeywords(byId('keywords').value.split(',').map(x=>x.trim()).filter(Boolean));download(await pdf.save(),'metadata-edited.pdf');setResult('Metadata updated.');return}
 if(id==='pdf-remove-metadata'){const pdf=await loadLib();pdf.setTitle('');pdf.setAuthor('');pdf.setSubject('');pdf.setKeywords([]);pdf.setProducer('');pdf.setCreator('');download(await pdf.save(),'metadata-clean.pdf');setResult('Common metadata fields removed.');return}
 if(['pdf-delete-pages','pdf-reorder','pdf-rotate','pdf-page-numbers','pdf-add-text','pdf-editor','pdf-watermark'].includes(id)){const bytes=await createProcessedBytes(false);download(bytes,`${id.replace('pdf-','')}-updated.pdf`);setResult(encryptedFallback?'Updated PDF created using compatible encrypted-file mode. Check the downloaded file before replacing your original.':'Updated PDF ready.');return}
 if(['pdf-paper-size','pdf-margin','pdf-crop'].includes(id)){const bytes=await createProcessedBytes(false);download(bytes,`${id.replace('pdf-','')}-updated.pdf`);setResult('Updated PDF ready.');return}
 if(id==='pdf-grayscale'){const src=await loadPdfJs(),out=await PDFLib.PDFDocument.create(),scale=Math.max(.7,Math.min(2.5,Number(byId('grayQuality').value)||1.5)),q=Math.max(.45,Math.min(.95,Number(byId('grayJpeg').value||82)/100));for(let i=1;i<=src.numPages;i++){const p=await src.getPage(i),vp=p.getViewport({scale:1}),c=await renderPageToCanvas(src,i,scale),ctx=c.getContext('2d'),im=ctx.getImageData(0,0,c.width,c.height),a=im.data;for(let j=0;j<a.length;j+=4){const y=Math.round(.299*a[j]+.587*a[j+1]+.114*a[j+2]);a[j]=a[j+1]=a[j+2]=y}ctx.putImageData(im,0,0);const blob=await new Promise(res=>c.toBlob(res,'image/jpeg',q)),img=await out.embedJpg(await blob.arrayBuffer()),op=out.addPage([vp.width,vp.height]);op.drawImage(img,{x:0,y:0,width:vp.width,height:vp.height})}download(await out.save(),'grayscale.pdf');setResult(`Converted ${src.numPages} page(s) to grayscale.`);return}
 if(id==='pdf-unlock'){const password=byId('pdfPassword').value;if(!password)throw Error('Enter the PDF password.');let src;try{src=await loadPdfJsWithPassword(primary,password)}catch(e){throw Error('Could not open this PDF with that password. Please check the password.')}const out=await PDFLib.PDFDocument.create();for(let i=1;i<=src.numPages;i++){const p=await src.getPage(i),vp=p.getViewport({scale:1}),c=await renderPageToCanvas(src,i,1.5),blob=await new Promise(res=>c.toBlob(res,'image/jpeg',.88)),img=await out.embedJpg(await blob.arrayBuffer()),op=out.addPage([vp.width,vp.height]);op.drawImage(img,{x:0,y:0,width:vp.width,height:vp.height})}download(await out.save(),'unlocked-copy.pdf');setResult('Unlocked copy created. Pages are rasterized to remove encryption safely.');return}
 if(id==='pdf-protect'){const password=byId('protectPassword').value,password2=byId('protectPassword2').value;if(!password)throw Error('Enter a password.');if(password.length<4)throw Error('Use at least 4 characters for the password.');if(password!==password2)throw Error('Passwords do not match.');if(!window.jspdf?.jsPDF)throw Error('PDF protection library did not load. Please refresh and try again.');const src=await loadPdfJs(),first=await src.getPage(1),firstVp=first.getViewport({scale:1}),orientation=firstVp.width>firstVp.height?'landscape':'portrait',doc=new window.jspdf.jsPDF({orientation,unit:'pt',format:[firstVp.width,firstVp.height],compress:true,encryption:{userPassword:password,ownerPassword:password+'-owner',userPermissions:['print']}});for(let i=1;i<=src.numPages;i++){const pg=await src.getPage(i),vp=pg.getViewport({scale:1}),canvas=await renderPageToCanvas(src,i,1.65),img=canvas.toDataURL('image/jpeg',.9);if(i>1)doc.addPage([vp.width,vp.height],vp.width>vp.height?'landscape':'portrait');doc.addImage(img,'JPEG',0,0,vp.width,vp.height,undefined,'FAST')}const blob=doc.output('blob');download(blob,'password-protected.pdf','application/pdf');setResult('Password-protected PDF created. Re-open the downloaded file to verify the password before deleting the original.');return}
 throw Error('This tool is not available yet.');
 }catch(e){setResult(e.message||'Could not process this file.',true)}finally{if(btn)btn.disabled=false}}
if(byId('runBtn'))byId('runBtn').addEventListener('click',run);
})();
