(()=>{
'use strict';
const $=id=>document.getElementById(id);
const P={
 en:{
  easy:[
   'Mars is often called the Red Planet because iron minerals in its soil give the surface a rusty color. A day on Mars is only a little longer than a day on Earth, but one Martian year lasts 687 Earth days.',
   'Honeybees communicate through movement. A worker bee can perform a small dance inside the hive to show other bees the direction and distance of a useful food source.',
   'The Moon does not make its own light. We see it because sunlight reflects from its surface. As the Moon travels around Earth, the bright part appears to change shape during the month.',
   'Ancient libraries were more than rooms filled with books. They were places where people copied texts, compared ideas, studied mathematics, and preserved knowledge for future generations.',
   'A rainbow appears when sunlight enters tiny drops of water and bends. The light separates into different colors, reflects inside the drop, and bends again as it leaves.',
   'The blue whale is the largest animal known to have lived on Earth. Even though it spends its life in the ocean, it is a mammal and must rise to the surface to breathe air.',
   'Volcanoes can build new land as well as destroy it. When hot rock reaches the surface and cools, layer after layer can slowly form mountains or even new islands.',
   'The first practical steam railways changed travel during the nineteenth century. Journeys that once took days by road could be completed more quickly and with heavier loads.',
   'Trees move water from their roots to their leaves through narrow tubes inside the trunk. Sunlight and moving air help pull this water upward even in very tall trees.',
   'The human heart works like a strong pump. It sends blood through a network of vessels that carries oxygen and nutrients to cells throughout the body.',
   'Dinosaurs lived on Earth for millions of years, but they were not all giant animals. Some species were small, fast, feathered, and very different from the huge skeletons shown in museums.',
   'Ocean tides are strongly influenced by the gravity of the Moon. As Earth rotates, coastlines move through areas of slightly higher and lower ocean water, producing regular changes in sea level.'
  ],
  medium:[
   'In 1969, Apollo 11 carried three astronauts toward the Moon. After travelling nearly 384,400 km, Neil Armstrong and Buzz Aldrin entered the lunar module (Eagle), while Michael Collins remained in orbit. The mission demonstrated how navigation, computing, engineering, and careful training could work together under extreme conditions.',
   'The Great Pyramid of Giza was built more than 4,500 years ago and originally stood about 146.6 m high. Its construction required careful surveying, organized labour, transport of enormous stone blocks, and precise alignment with the surrounding landscape.',
   'Earth completes one orbit around the Sun in about 365.25 days, which is why the calendar occasionally needs a leap day. Without that adjustment, the calendar would slowly drift away from the seasons by roughly 1 day every 4 years.',
   'The printing press transformed the spread of information in Europe after the 15th century. Books that had once been copied by hand could be produced in larger numbers, lowering costs and allowing scientific, religious, and political ideas to travel farther.',
   'A healthy adult human body contains roughly 5 litres of blood. Red blood cells transport oxygen using haemoglobin, while white blood cells form part of the immune system; platelets help control bleeding when a blood vessel is damaged.',
   'Saturn is famous for a ring system made mainly of ice, rock, and dust. The rings extend for hundreds of thousands of kilometres, yet many parts are surprisingly thin-often far thinner than the planet is wide.',
   'During a total solar eclipse, the Moon passes directly between Earth and the Sun. For a few minutes, observers inside a narrow path can see the faint solar corona (the Sun\'s outer atmosphere) while the bright surface is hidden.',
   'The Roman road network eventually stretched across more than 80,000 km of major routes. Engineers used layered materials, drainage, bridges, and carefully chosen gradients so soldiers, officials, merchants, and messages could move efficiently.',
   'Water expands by about 9% when it freezes. This unusual property means ice is less dense than liquid water, so it floats; lakes can freeze at the surface while liquid water remains below, helping aquatic life survive cold winters.',
   'The International Space Station travels at roughly 28,000 km/h and circles Earth about once every 90 minutes. Astronauts aboard it experience repeated sunrises and sunsets while conducting experiments in microgravity.',
   'In photography, an aperture written as f/2.8 allows more light through the lens than f/8. A faster shutter such as 1/1000 s can freeze motion, while a slower exposure such as 1/15 s may show deliberate blur.',
   'A map scale of 1:50,000 means that 1 cm on the map represents 50,000 cm (500 m) on the ground. Scale, contour lines, symbols, and a north reference work together to turn a flat drawing into useful geographic information.'
  ],
  hard:[
   'During the 19th century, scientists gradually connected electricity and magnetism through experiment and mathematics. By 1865, James Clerk Maxwell had expressed several relationships in a unified theory; later work showed that visible light belongs to the electromagnetic spectrum, alongside radio waves, microwaves, X-rays, and other forms of radiation.',
   'When the Rosetta Stone was discovered in 1799, its inscriptions presented essentially the same decree in Greek, Demotic, and Egyptian hieroglyphs. Because scholars could already read Greek, the stone became a crucial reference for deciphering a writing system that had remained mysterious for centuries.',
   'A modern processor may contain billions of transistors, each acting as an extremely small electronic switch. These switches are organized into logic gates, memory structures, and control circuits; billions of operations per second can emerge from repeated combinations of simple 0/1 states.',
   'Radiocarbon dating estimates the age of once-living material by measuring carbon-14 (C-14), a radioactive isotope with a half-life of about 5,730 years. The method is powerful, but calibration is necessary because the concentration of atmospheric carbon-14 has not remained perfectly constant through time.',
   'The speed of light in vacuum is exactly 299,792,458 m/s. Einstein\'s equation E = mc^2 links mass and energy, but the familiar expression is only one result within a broader framework in which measurements of time and distance depend on the observer\'s relative motion.',
   'In 1914, the Panama Canal opened a route between the Atlantic and Pacific oceans without requiring ships to travel around South America. Its lock system raises vessels to Gatun Lake and lowers them again; engineering decisions had to account for rainfall, disease control, excavation, and a difference in terrain of many metres.',
   'A pH value is logarithmic rather than linear: a solution at pH 3 has 10x the hydrogen-ion concentration of a solution at pH 4, and 100x that of pH 5. This is why apparently small numerical differences can represent large chemical changes.',
   'The expression P(A|B) describes the probability of event A given that B has occurred. Bayes\' theorem, P(A|B) = P(B|A)P(A)/P(B), provides a formal way to update an earlier belief when new evidence becomes available, provided the relevant probabilities are defined consistently.',
   'DNA stores biological information using sequences built from four nucleotide bases: A, C, G, and T. A human genome contains roughly 3.2 billion base pairs, yet only a portion directly codes for proteins; regulation, structure, and non-coding regions also influence how cells function.',
   'On a logarithmic earthquake-magnitude scale, a one-unit increase does not mean "one more unit" of physical effect. Seismic-wave amplitude changes by a factor of 10, while the energy released increases by roughly 31.6x, so a magnitude-7 event is fundamentally different from a magnitude-6 event.',
   'The Treaty of Versailles was signed on 28 June 1919, exactly five years after the assassination of Archduke Franz Ferdinand. Its territorial, military, and financial clauses reshaped post-war Europe, but historians continue to debate how strongly those terms contributed to later political instability.',
   'A spacecraft travelling from Earth to another planet rarely aims at the planet\'s current position. Mission planners calculate where the target will be months later, then choose a transfer trajectory; small corrections (delta-v) made at the right time can change the arrival point by thousands of kilometres.'
  ]
 },
 hi:{
  easy:['मंगल ग्रह को लाल ग्रह कहा जाता है क्योंकि उसकी मिट्टी में लोहे वाले खनिज सतह को लाल रंग देते हैं। मंगल का एक दिन पृथ्वी के दिन से थोड़ा लंबा होता है।','चंद्रमा अपना प्रकाश नहीं बनाता। हम उसे इसलिए देखते हैं क्योंकि सूर्य का प्रकाश उसकी सतह से लौटकर हमारी आंखों तक पहुंचता है।','पेड़ अपनी जड़ों से पानी लेते हैं और उसे तने के भीतर बनी पतली नलियों से पत्तियों तक पहुंचाते हैं। सूर्य का प्रकाश इस प्रक्रिया में महत्वपूर्ण भूमिका निभाता है।'],
  medium:['सन् 1969 में अपोलो 11 मिशन तीन अंतरिक्ष यात्रियों को चंद्रमा की ओर ले गया। लगभग 384,400 किमी की यात्रा के बाद नील आर्मस्ट्रांग और बज़ एल्ड्रिन चंद्र सतह पर उतरे, जबकि माइकल कॉलिन्स कक्षा में रहे।','पृथ्वी सूर्य की एक परिक्रमा लगभग 365.25 दिनों में पूरी करती है। इसी अतिरिक्त समय को संतुलित करने के लिए लगभग हर 4 वर्ष में फरवरी के महीने में एक अतिरिक्त दिन जोड़ा जाता है।','मानव शरीर में लगभग 5 लीटर रक्त होता है। लाल रक्त कोशिकाएं ऑक्सीजन पहुंचाती हैं, जबकि श्वेत रक्त कोशिकाएं शरीर की प्रतिरक्षा प्रणाली का हिस्सा होती हैं।'],
  hard:['रेडियोकार्बन डेटिंग में कार्बन-14 (C-14) की मात्रा मापकर कभी जीवित रहे पदार्थ की आयु का अनुमान लगाया जाता है। इस समस्थानिक की अर्ध-आयु लगभग 5,730 वर्ष है, इसलिए परिणामों की उचित कैलिब्रेशन आवश्यक होती है।','प्रकाश की निर्वात में गति ठीक 299,792,458 मीटर/सेकंड पर परिभाषित है। आइंस्टीन का समीकरण E = mc^2 द्रव्यमान और ऊर्जा के संबंध को दर्शाता है, लेकिन सापेक्षता का सिद्धांत समय और दूरी के मापन पर भी गहरा प्रभाव डालता है।','pH पैमाना रैखिक नहीं बल्कि लघुगणकीय है: pH 3 वाले घोल में हाइड्रोजन आयन की सांद्रता pH 4 की तुलना में 10x और pH 5 की तुलना में 100x होती है।']
 }
};
let words=[],states=[],spans=[],index=0,mode='normal',wrongKeys=0,printableKeys=0,completedChars=0,currentTouched=false,running=false,paused=false,ended=false,timerStarted=false,timer=null,lastTick=0,activeMs=0,totalSec=300,remaining=300,lastLineTop=null,passageNo=0;
function pool(){return P[$('ttLang').value][$('ttDifficulty').value]}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function buildWords(){const ps=shuffle(pool()),target=Math.max(260,Math.ceil(Number($('ttDuration').value)/60*300));let arr=[],i=0;while(arr.length<target){arr.push(...ps[i%ps.length].split(/\s+/));i++}words=arr;states=new Array(words.length).fill(null);passageNo++;render(true);$('ttPassageCount').textContent='Passage '+passageNo;$('ttDifficultyBadge').textContent=$('ttDifficulty').selectedOptions[0].text+' · educational'}
function render(reset=false){const f=$('ttFlow');f.textContent='';spans=[];words.forEach((w,i)=>{const s=document.createElement('span');s.className='tt-word '+(i===index?'current':i<index?(states[i]?.ok?'locked-ok':'locked-bad'):'upcoming');s.dataset.i=i;s.textContent=w;f.appendChild(s);spans.push(s);if(i<words.length-1)f.appendChild(document.createTextNode(' '))});if(reset){$('ttWindow').scrollTop=0;requestAnimationFrame(()=>{lastLineTop=spans[index]?.offsetTop??0})}labels()}
function appendMore(){const extra=shuffle(pool()).join(' ').split(/\s+/);const start=words.length;words.push(...extra);states.push(...new Array(extra.length).fill(null));extra.forEach((w,o)=>{if($('ttFlow').childNodes.length)$('ttFlow').appendChild(document.createTextNode(' '));const s=document.createElement('span');s.className='tt-word upcoming';s.dataset.i=start+o;s.textContent=w;$('ttFlow').appendChild(s);spans.push(s)})}
function fmt(s){s=Math.max(0,Math.ceil(s));return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function labels(){$('ttCurrentLabel').textContent=ended?'Test finished.':paused?'Paused.':running&&!timerStarted?'Ready — start typing to begin the timer.':running?`Word ${index+1} · ${words[index]||''}`:'Press Start Test to begin.'}
function stats(){const mins=Math.max(activeMs/60000,1/60000),live=completedChars+Array.from($('ttInput').value||'').length,acc=printableKeys?Math.max(0,Math.round((printableKeys-wrongKeys)/printableKeys*100)):100;$('ttWpm').textContent=activeMs?Math.max(0,Math.round((live/5)/mins)):0;$('ttCpm').textContent=activeMs?Math.max(0,Math.round(live/mins)):0;$('ttAcc').textContent=acc+'%';$('ttErrors').textContent=wrongKeys;$('ttTime').textContent=fmt(remaining);$('ttBar').style.width=Math.min(100,Math.max(0,(totalSec-remaining)/totalSec*100))+'%'}
function beginTiming(){if(!running||paused||ended||timerStarted)return;timerStarted=true;$('ttPause').disabled=false;window.DoKitlyAnalytics?.trackProcessStarted({tool_name:'Online Typing Test'});startTimer();labels()}
function startTimer(){clearInterval(timer);lastTick=performance.now();timer=setInterval(()=>{if(!running||paused)return;const n=performance.now(),d=(n-lastTick)/1000;lastTick=n;remaining=Math.max(0,remaining-d);activeMs+=d*1000;stats();if(remaining<=0)finish()},100)}
function setPrimary(){const b=$('ttPrimary');b.textContent=running||paused?'✓ Finish Test':'▶ Start Test';b.classList.toggle('finish-state',running||paused)}
function start(){if(ended)reset(false);running=true;paused=false;ended=false;timerStarted=false;$('ttInput').disabled=false;$('ttPause').disabled=true;$('ttPause').textContent='Ⅱ Pause';setPrimary();$('ttInput').focus();$('ttResult').hidden=true;labels()}
function finish(){if(ended&&!running)return;const hadTiming=timerStarted;clearInterval(timer);timer=null;running=false;paused=false;ended=true;timerStarted=false;$('ttInput').disabled=true;$('ttPause').disabled=true;$('ttPause').textContent='Ⅱ Pause';stats();$('ttResult').hidden=false;$('ttResult').className='tt-result ok';$('ttResult').textContent=`Finished - ${$('ttWpm').textContent} WPM · ${$('ttCpm').textContent} CPM · ${$('ttAcc').textContent} accuracy · ${wrongKeys} errors.`;setPrimary();labels();if(hadTiming)window.DoKitlyAnalytics?.trackProcessCompleted({tool_name:'Online Typing Test',success:true});exitFocus()}
function pause(){if(!running||ended||!timerStarted)return;if(!paused){paused=true;clearInterval(timer);timer=null;$('ttInput').disabled=true;$('ttPause').textContent='▶ Resume'}else{paused=false;$('ttInput').disabled=false;$('ttPause').textContent='Ⅱ Pause';startTimer();$('ttInput').focus()}labels()}
function clearTyped(){[...$('ttTypedStream').querySelectorAll('.tt-typed-token')].forEach(x=>x.remove());$('ttEmptyHint').hidden=false;$('ttInput').value='';$('ttInput').style.width='66px';$('ttTypedViewport').scrollTop=0}
function reset(rebuild=true){clearInterval(timer);timer=null;running=paused=ended=timerStarted=false;wrongKeys=printableKeys=completedChars=0;activeMs=0;index=0;currentTouched=false;totalSec=Number($('ttDuration').value);remaining=totalSec;clearTyped();$('ttInput').disabled=true;$('ttPause').disabled=true;$('ttPause').textContent='Ⅱ Pause';if(rebuild)buildWords();else{states=new Array(words.length).fill(null);render(true)}$('ttResult').hidden=true;stats();setPrimary();labels()}
function addToken(text,ok){$('ttEmptyHint').hidden=true;const s=document.createElement('span');s.className='tt-typed-token '+(ok?'ok':'bad');s.textContent=text;$('ttTypedStream').insertBefore(s,$('ttInput'));requestAnimationFrame(()=>{$('ttTypedViewport').scrollTop=$('ttTypedViewport').scrollHeight})}
function scrollRef(prev){const cur=spans[index];if(!cur)return;const top=cur.offsetTop,base=lastLineTop??prev??top;if(Math.abs(top-base)>4){const lh=parseFloat(getComputedStyle($('ttFlow')).lineHeight)||36;$('ttWindow').scrollTo({top:Math.max(0,top-lh*1.02),behavior:'smooth'});lastLineTop=top}}
function commit(){const inp=$('ttInput'),typed=inp.value,expected=words[index]||'';if(!typed)return;const old=spans[index],prev=old?.offsetTop??lastLineTop,exact=typed===expected,referenceOk=exact&&!currentTouched,typedOk=exact;states[index]={ok:referenceOk,typed,finalOk:typedOk,hadMistake:currentTouched};if(old){old.className='tt-word '+(referenceOk?'locked-ok':'locked-bad')}addToken(typed,typedOk);completedChars+=Array.from(typed).length+1;index++;inp.value='';inp.style.width='66px';currentTouched=false;if(index>=words.length-25)appendMore();if(spans[index])spans[index].className='tt-word current';labels();requestAnimationFrame(()=>scrollRef(prev));stats()}
function modeHelp(){const t={normal:'Normal · correct inside current word; mistake history stays marked above and still counts.',strict:'Strict · correction is allowed, but every mistake remains in the reference history and accuracy.',god:'God · Backspace disabled; every key is final.'};$('ttModeHelp').textContent=t[mode]}
function enterFocus(){document.body.classList.add('tt-focus');$('ttExitFocus').style.display='inline-flex';if(running&&!paused)$('ttInput').focus()}
function exitFocus(){document.body.classList.remove('tt-focus');$('ttExitFocus').style.display='none'}
$('ttInput').addEventListener('input',()=>{if(running&&!paused&&!ended&&!timerStarted&&$('ttInput').value)beginTiming();$('ttInput').style.width=Math.max(66,Math.min(360,(Array.from($('ttInput').value).length+1)*10+25))+'px';stats()});
$('ttInput').addEventListener('keydown',e=>{if(!running||paused||ended)return;if(e.key==='Backspace'){if(mode==='god'){e.preventDefault();return}if(!$('ttInput').value)e.preventDefault();return}if(e.code==='Space'||e.key===' '){e.preventDefault();commit();return}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End','PageUp','PageDown','Tab','Enter','Delete'].includes(e.key)){e.preventDefault();return}if((e.ctrlKey||e.metaKey)&&['v','x','z','y'].includes(e.key.toLowerCase())){e.preventDefault();return}if(e.key.length===1&&!e.ctrlKey&&!e.metaKey&&!e.altKey){beginTiming();const pos=Array.from($('ttInput').value).length,exp=Array.from(words[index]||'')[pos]||'';printableKeys++;if(e.key!==exp){wrongKeys++;currentTouched=true}setTimeout(stats,0)}});
$('ttInput').addEventListener('paste',e=>e.preventDefault());$('ttTypebox').addEventListener('click',()=>{if(running&&!paused)$('ttInput').focus()});
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{if(running||paused)return;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;modeHelp();reset(false)}));
$('ttPrimary').addEventListener('click',()=>running||paused?finish():start());$('ttPause').addEventListener('click',pause);$('ttRestart').addEventListener('click',()=>reset(false));$('ttNew').addEventListener('click',()=>{if(!running&&!paused)reset(true)});$('ttFocus').addEventListener('click',enterFocus);$('ttExitFocus').addEventListener('click',exitFocus);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.body.classList.contains('tt-focus'))exitFocus()});['ttLang','ttDuration','ttDifficulty'].forEach(id=>$(id).addEventListener('change',()=>{if(!running&&!paused)reset(true)}));
modeHelp();buildWords();reset(false);
})();