(()=>{
const $=id=>document.getElementById(id), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const out=$('mathOut');
function ready(){return typeof nerdamer==='function'}
function show(title,exact,extra=''){if(!out)return;out.innerHTML=`<div class="math-result-title">${esc(title)}</div><div class="math-result-main">${esc(exact)}</div>${extra}`;out.classList.add('has-result')}
function err(e){show('Could not solve',e?.message||String(e),'<small>Try explicit multiplication such as 2*x, balanced brackets, and standard function names like sin(x), log(x), sqrt(x).</small>')}
function exactAndDecimal(expr){let exact=String(expr),dec='';try{dec=nerdamer(exact).evaluate().text('decimals')}catch{}return dec&&dec!==exact?`<div class="math-subresult"><b>Decimal approximation</b><span>${esc(dec)}</span></div>`:''}
function needEngine(){if(ready())return true;show('Math engine unavailable','The symbolic library did not load. Check your connection and reload this page.');return false}
function normEq(s){return s.trim().replace(/π/g,'pi').replace(/∞/g,'Infinity')}

function equation(){if(!needEngine())return;try{const raw=$('expr').value.trim(),vars=($('vars')?.value||'x').split(',').map(x=>x.trim()).filter(Boolean);if(!raw)throw Error('Enter an equation first.');const eqs=raw.split(/\n|;/).map(normEq).filter(Boolean);let sol;if(eqs.length>1){sol=nerdamer.solveEquations(eqs,vars);show('System solution',Array.isArray(sol)?sol.map(x=>Array.isArray(x)?`${x[0]} = ${x[1]}`:String(x)).join(' ; '):String(sol),'<small>Multiple equations are solved together using the variables you supplied.</small>')}else{const v=vars[0]||'x';sol=nerdamer(eqs[0]).solveFor(v);show(`Solution for ${v}`,sol.toString()||'No symbolic solution found',exactAndDecimal(sol.toString()))}}catch(e){err(e)}}
function diff(){if(!needEngine())return;try{const ex=normEq($('expr').value),v=$('variable').value.trim()||'x',o=Math.max(1,Math.min(8,+$('order').value||1));if(!ex)throw Error('Enter a function first.');const q=o===1?`diff(${ex},${v})`:`diff(${ex},${v},${o})`,ans=nerdamer(q).toString();show(`${o===1?'Derivative':o+'th derivative'} with respect to ${v}`,ans,exactAndDecimal(ans))}catch(e){err(e)}}
function integrate(){if(!needEngine())return;try{const ex=normEq($('expr').value),v=$('variable').value.trim()||'x';if(!ex)throw Error('Enter a function first.');let ans,label;if($('integralType').value==='definite'){const a=normEq($('from').value),b=normEq($('to').value);ans=nerdamer(`defint(${ex},${a},${b},${v})`).toString();label=`Definite integral from ${a} to ${b}`}else{ans=nerdamer(`integrate(${ex},${v})`).toString();label=`Indefinite integral with respect to ${v}`;ans+=' + C'}show(label,ans,exactAndDecimal(ans.replace(/ \+ C$/,'')))}catch(e){err(e)}}
function limit(){if(!needEngine())return;try{const ex=normEq($('expr').value),v=$('variable').value.trim()||'x',to=normEq($('to').value||'0');const ans=nerdamer(`limit(${ex},${v},${to})`).toString();show(`Limit as ${v} → ${to}`,ans,exactAndDecimal(ans))}catch(e){err(e)}}
function laplace(inv=false){if(!needEngine())return;try{const ex=normEq($('expr').value),a=$('variable').value.trim()||(inv?'s':'t'),b=$('transformVar').value.trim()||(inv?'t':'s'),fn=inv?'ilt':'laplace';const ans=nerdamer(`${fn}(${ex},${a},${b})`).toString();show(inv?'Inverse Laplace transform':'Laplace transform',ans,exactAndDecimal(ans))}catch(e){err(e)}}

function parseMatrix(text){const rows=text.trim().split(/\n/).map(r=>r.trim()).filter(Boolean).map(r=>r.split(/[ ,]+/).filter(Boolean).map(Number));if(!rows.length||rows.some(r=>r.some(v=>!Number.isFinite(v))))throw Error('Enter matrix rows using spaces or commas.');const n=rows[0].length;if(!n||rows.some(r=>r.length!==n))throw Error('Every matrix row must have the same number of values.');return rows}
function matrixFmt(A){return '<div class="matrix-view">'+A.map(r=>'<div>'+r.map(v=>`<span>${Number.isFinite(v)?Number(v.toFixed(8)):v}</span>`).join('')+'</div>').join('')+'</div>'}
function transpose(A){return A[0].map((_,j)=>A.map(r=>r[j]))}
function det(A){if(A.length!==A[0].length)throw Error('Determinant requires a square matrix.');if(A.length===1)return A[0][0];if(A.length===2)return A[0][0]*A[1][1]-A[0][1]*A[1][0];return A[0].reduce((s,v,j)=>s+((j%2?-1:1)*v*det(A.slice(1).map(r=>r.filter((_,k)=>k!==j)))),0)}
function rref(A){A=A.map(r=>r.slice());let lead=0;for(let r=0;r<A.length;r++){if(lead>=A[0].length)break;let i=r;while(Math.abs(A[i][lead])<1e-12){i++;if(i===A.length){i=r;lead++;if(lead===A[0].length)return A}}[A[i],A[r]]=[A[r],A[i]];let val=A[r][lead];A[r]=A[r].map(x=>x/val);for(i=0;i<A.length;i++)if(i!==r){val=A[i][lead];A[i]=A[i].map((x,j)=>x-val*A[r][j])}lead++}return A.map(r=>r.map(x=>Math.abs(x)<1e-10?0:x))}
function inverse(A){if(A.length!==A[0].length)throw Error('Inverse requires a square matrix.');const n=A.length,aug=A.map((r,i)=>[...r,...Array.from({length:n},(_,j)=>i===j?1:0)]),R=rref(aug);for(let i=0;i<n;i++)for(let j=0;j<n;j++)if(Math.abs(R[i][j]-(i===j?1:0))>1e-7)throw Error('This matrix is singular and has no inverse.');return R.map(r=>r.slice(n))}
function multiply(A,B){if(A[0].length!==B.length)throw Error('A columns must equal B rows.');return A.map(r=>B[0].map((_,j)=>r.reduce((s,v,k)=>s+v*B[k][j],0)))}
function matrix(){try{const A=parseMatrix($('matrixA').value),op=$('matrixOp').value;let ans,title;if(op==='det'){ans=det(A);title='Determinant';show(title,String(ans))}else if(op==='transpose'){const R=transpose(A);out.innerHTML='<div class="math-result-title">Transpose</div>'+matrixFmt(R)}else if(op==='inverse'){const R=inverse(A);out.innerHTML='<div class="math-result-title">Inverse</div>'+matrixFmt(R)}else if(op==='rref'){const R=rref(A);out.innerHTML='<div class="math-result-title">Reduced row echelon form</div>'+matrixFmt(R)}else if(op==='multiply'){const B=parseMatrix($('matrixB').value),R=multiply(A,B);out.innerHTML='<div class="math-result-title">A × B</div>'+matrixFmt(R)}else if(op==='add'){const B=parseMatrix($('matrixB').value);if(A.length!==B.length||A[0].length!==B[0].length)throw Error('A and B must have the same dimensions.');const R=A.map((r,i)=>r.map((v,j)=>v+B[i][j]));out.innerHTML='<div class="math-result-title">A + B</div>'+matrixFmt(R)}else if(op==='solve'){const b=($('vectorB').value||'').split(/[ ,\n]+/).filter(Boolean).map(Number);if(A.length!==A[0].length||b.length!==A.length||b.some(x=>!Number.isFinite(x)))throw Error('For Ax = b, enter a square A and one b value per row.');const R=rref(A.map((r,i)=>[...r,b[i]]));const x=R.map(r=>r[r.length-1]);show('Solution vector x',`[${x.map(v=>Number(v.toFixed(8))).join(', ')}]`)}out.classList.add('has-result')}catch(e){err(e)}}

const nums=s=>(String(s).match(/[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?/gi)||[]).map(Number).filter(Number.isFinite), mean=a=>a.reduce((s,x)=>s+x,0)/a.length, quant=(a,q)=>{a=[...a].sort((x,y)=>x-y);const p=(a.length-1)*q,b=Math.floor(p),r=p-b;return a[b+1]!==undefined?a[b]+r*(a[b+1]-a[b]):a[b]};
function statistics(){try{const a=nums($('dataX').value);if(!a.length)throw Error('Enter at least one numeric value.');const m=mean(a),popVar=mean(a.map(x=>(x-m)**2)),sampleVar=a.length>1?a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1):0;const counts={};a.forEach(x=>counts[x]=(counts[x]||0)+1);const max=Math.max(...Object.values(counts)),modes=max>1?Object.keys(counts).filter(k=>counts[k]===max).join(', '):'No repeated mode';let html=`<div class="stat-grid"><span><b>Count</b>${a.length}</span><span><b>Mean</b>${m.toFixed(6)}</span><span><b>Median</b>${quant(a,.5).toFixed(6)}</span><span><b>Mode</b>${modes}</span><span><b>Population variance</b>${popVar.toFixed(6)}</span><span><b>Population SD</b>${Math.sqrt(popVar).toFixed(6)}</span><span><b>Sample variance</b>${sampleVar.toFixed(6)}</span><span><b>Q1 / Q3</b>${quant(a,.25).toFixed(4)} / ${quant(a,.75).toFixed(4)}</span></div>`;const y=nums($('dataY').value);if(y.length){if(y.length!==a.length)throw Error('X and Y lists must have the same number of values for correlation.');const mx=mean(a),my=mean(y),cov=a.reduce((s,x,i)=>s+(x-mx)*(y[i]-my),0)/a.length,sx=Math.sqrt(mean(a.map(x=>(x-mx)**2))),sy=Math.sqrt(mean(y.map(x=>(x-my)**2))),corr=sx&&sy?cov/(sx*sy):NaN,slope=sx?cov/(sx*sx):NaN,intercept=my-slope*mx;html+=`<div class="math-subresult"><b>Correlation & regression</b><span>r = ${corr.toFixed(6)} • y ≈ ${slope.toFixed(6)}x + ${intercept.toFixed(6)}</span></div>`}out.innerHTML='<div class="math-result-title">Statistics</div>'+html;out.classList.add('has-result')}catch(e){err(e)}}

function fval(expr,x){if(!needEngine())throw Error('Math engine unavailable');const v=nerdamer(expr,{x:String(x)}).evaluate().text('decimals');const n=Number(v);if(!Number.isFinite(n))throw Error('Function did not evaluate to a finite real number.');return n}
function numerical(){try{const ex=normEq($('expr').value),method=$('numMethod').value,tol=Math.max(1e-12,Number($('tol').value)||1e-7),iters=Math.max(5,Math.min(500,+$('iters').value||100));if(!ex)throw Error('Enter f(x).');if(method==='bisection'){let a=+$('a').value,b=+$('b').value,fa=fval(ex,a),fb=fval(ex,b);if(fa*fb>0)throw Error('Bisection requires opposite signs at a and b.');let c,fc,k=0;for(;k<iters;k++){c=(a+b)/2;fc=fval(ex,c);if(Math.abs(fc)<tol||Math.abs(b-a)/2<tol)break;if(fa*fc<=0){b=c;fb=fc}else{a=c;fa=fc}}show('Bisection root',`${c}`,`<div class="math-subresult"><b>Iterations</b><span>${k+1} • f(x) ≈ ${fc}</span></div>`)}else if(method==='newton'){let x=+$('x0').value,k=0,fx;for(;k<iters;k++){fx=fval(ex,x);const h=1e-6*(1+Math.abs(x)),d=(fval(ex,x+h)-fval(ex,x-h))/(2*h);if(Math.abs(d)<1e-14)throw Error('Derivative became too small for Newton-Raphson.');const nx=x-fx/d;if(Math.abs(nx-x)<tol){x=nx;break}x=nx}show('Newton-Raphson root',`${x}`,`<div class="math-subresult"><b>Iterations</b><span>${k+1} • f(x) ≈ ${fval(ex,x)}</span></div>`)}else{let a=+$('a').value,b=+$('b').value,n=Math.max(2,Math.min(10000,+$('n').value||100));if(method==='simpson'&&n%2)n++;const h=(b-a)/n;let sum;if(method==='trapezoid'){sum=.5*(fval(ex,a)+fval(ex,b));for(let i=1;i<n;i++)sum+=fval(ex,a+i*h);sum*=h}else{sum=fval(ex,a)+fval(ex,b);for(let i=1;i<n;i++)sum+=(i%2?4:2)*fval(ex,a+i*h);sum*=h/3}show(method==='simpson'?'Simpson numerical integral':'Trapezoidal numerical integral',String(sum),`<div class="math-subresult"><b>Intervals</b><span>${n} on [${a}, ${b}]</span></div>`)}}catch(e){err(e)}}

const type=document.body.dataset.mathTool;const btn=$('solveBtn');if(btn){btn.addEventListener('click',()=>({equation:equation,differentiation:diff,integration:integrate,limit:limit,laplace:()=>laplace(false),'inverse-laplace':()=>laplace(true),matrix,statistics,numerical}[type]||(()=>{}))());}
if(type==='integration')$('integralType')?.addEventListener('change',()=>document.body.classList.toggle('show-bounds',$('integralType').value==='definite'));
if(type==='matrix')$('matrixOp')?.addEventListener('change',()=>{const v=$('matrixOp').value;document.body.classList.toggle('matrix-needs-b',v==='add'||v==='multiply');document.body.classList.toggle('matrix-needs-vector',v==='solve')});
if(type==='numerical')$('numMethod')?.addEventListener('change',()=>{document.body.dataset.numMethod=$('numMethod').value});
})();
